// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: management.sql

package postgresquery

import (
	"context"
	"database/sql"
)

const backfillNodeSettingsNetwork = `-- name: BackfillNodeSettingsNetwork :execrows
UPDATE node_settings
SET network = $1
WHERE id = 1 AND storage_mode = $2 AND network = ''
`

type BackfillNodeSettingsNetworkParams struct {
	Network     string
	StorageMode string
}

func (q *Queries) BackfillNodeSettingsNetwork(ctx context.Context, arg BackfillNodeSettingsNetworkParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, backfillNodeSettingsNetwork, arg.Network, arg.StorageMode)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getCommitTimestamp = `-- name: GetCommitTimestamp :one
SELECT timestamp
FROM commit_timestamp
WHERE id = 1
`

func (q *Queries) GetCommitTimestamp(ctx context.Context) (sql.NullInt64, error) {
	row := q.db.QueryRowContext(ctx, getCommitTimestamp)
	var timestamp sql.NullInt64
	err := row.Scan(&timestamp)
	return timestamp, err
}

const getNodeSettings = `-- name: GetNodeSettings :one
SELECT storage_mode, network
FROM node_settings
WHERE id = 1
`

type GetNodeSettingsRow struct {
	StorageMode string
	Network     string
}

func (q *Queries) GetNodeSettings(ctx context.Context) (GetNodeSettingsRow, error) {
	row := q.db.QueryRowContext(ctx, getNodeSettings)
	var i GetNodeSettingsRow
	err := row.Scan(&i.StorageMode, &i.Network)
	return i, err
}

const insertNodeSettings = `-- name: InsertNodeSettings :execrows
INSERT INTO node_settings (id, storage_mode, network)
VALUES (1, $1, $2)
ON CONFLICT (id) DO NOTHING
`

type InsertNodeSettingsParams struct {
	StorageMode string
	Network     string
}

func (q *Queries) InsertNodeSettings(ctx context.Context, arg InsertNodeSettingsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertNodeSettings, arg.StorageMode, arg.Network)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setCommitTimestamp = `-- name: SetCommitTimestamp :exec
INSERT INTO commit_timestamp (id, timestamp)
VALUES (1, $1)
ON CONFLICT (id) DO UPDATE SET timestamp = excluded.timestamp
`

func (q *Queries) SetCommitTimestamp(ctx context.Context, timestamp sql.NullInt64) error {
	_, err := q.db.ExecContext(ctx, setCommitTimestamp, timestamp)
	return err
}
