// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: management.sql

package postgresquery

import (
	"context"
	"database/sql"
)

const backfillNodeSettingsNetwork = `-- name: BackfillNodeSettingsNetwork :execrows
UPDATE node_settings
SET network = $1
WHERE id = 1 AND storage_mode = $2 AND network = ''
`

type BackfillNodeSettingsNetworkParams struct {
	Network     string
	StorageMode string
}

func (q *Queries) BackfillNodeSettingsNetwork(ctx context.Context, arg BackfillNodeSettingsNetworkParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, backfillNodeSettingsNetwork, arg.Network, arg.StorageMode)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getCommitTimestamp = `-- name: GetCommitTimestamp :one
SELECT timestamp
FROM commit_timestamp
WHERE id = 1
`

func (q *Queries) GetCommitTimestamp(ctx context.Context) (sql.NullInt64, error) {
	row := q.db.QueryRowContext(ctx, getCommitTimestamp)
	var timestamp sql.NullInt64
	err := row.Scan(&timestamp)
	return timestamp, err
}

const getNodeSettings = `-- name: GetNodeSettings :one
SELECT storage_mode, network
FROM node_settings
WHERE id = 1
`

type GetNodeSettingsRow struct {
	StorageMode string
	Network     string
}

func (q *Queries) GetNodeSettings(ctx context.Context) (GetNodeSettingsRow, error) {
	row := q.db.QueryRowContext(ctx, getNodeSettings)
	var i GetNodeSettingsRow
	err := row.Scan(&i.StorageMode, &i.Network)
	return i, err
}

const getNodeSettingsGates = `-- name: GetNodeSettingsGates :many
SELECT name, value
FROM node_settings_gate
`

type GetNodeSettingsGatesRow struct {
	Name  string
	Value string
}

func (q *Queries) GetNodeSettingsGates(ctx context.Context) ([]GetNodeSettingsGatesRow, error) {
	rows, err := q.db.QueryContext(ctx, getNodeSettingsGates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetNodeSettingsGatesRow{}
	for rows.Next() {
		var i GetNodeSettingsGatesRow
		if err := rows.Scan(&i.Name, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertNodeSettings = `-- name: InsertNodeSettings :execrows
INSERT INTO node_settings (id, storage_mode, network)
VALUES (1, $1, $2)
ON CONFLICT (id) DO NOTHING
`

type InsertNodeSettingsParams struct {
	StorageMode string
	Network     string
}

func (q *Queries) InsertNodeSettings(ctx context.Context, arg InsertNodeSettingsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertNodeSettings, arg.StorageMode, arg.Network)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertNodeSettingsGateIfAbsent = `-- name: InsertNodeSettingsGateIfAbsent :execrows
INSERT INTO node_settings_gate (name, value, recorded_epoch, recorded_slot)
VALUES ($1, $2, $3, $4)
ON CONFLICT (name) DO NOTHING
`

type InsertNodeSettingsGateIfAbsentParams struct {
	Name          string
	Value         string
	RecordedEpoch int64
	RecordedSlot  int64
}

func (q *Queries) InsertNodeSettingsGateIfAbsent(ctx context.Context, arg InsertNodeSettingsGateIfAbsentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertNodeSettingsGateIfAbsent,
		arg.Name,
		arg.Value,
		arg.RecordedEpoch,
		arg.RecordedSlot,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setCommitTimestamp = `-- name: SetCommitTimestamp :exec
INSERT INTO commit_timestamp (id, timestamp)
VALUES (1, $1)
ON CONFLICT (id) DO UPDATE SET timestamp = excluded.timestamp
`

func (q *Queries) SetCommitTimestamp(ctx context.Context, timestamp sql.NullInt64) error {
	_, err := q.db.ExecContext(ctx, setCommitTimestamp, timestamp)
	return err
}

const upsertNodeSettingsGate = `-- name: UpsertNodeSettingsGate :exec
INSERT INTO node_settings_gate (name, value, recorded_epoch, recorded_slot)
VALUES ($1, $2, $3, $4)
ON CONFLICT (name) DO UPDATE SET
    value = excluded.value,
    recorded_epoch = excluded.recorded_epoch,
    recorded_slot = excluded.recorded_slot
`

type UpsertNodeSettingsGateParams struct {
	Name          string
	Value         string
	RecordedEpoch int64
	RecordedSlot  int64
}

func (q *Queries) UpsertNodeSettingsGate(ctx context.Context, arg UpsertNodeSettingsGateParams) error {
	_, err := q.db.ExecContext(ctx, upsertNodeSettingsGate,
		arg.Name,
		arg.Value,
		arg.RecordedEpoch,
		arg.RecordedSlot,
	)
	return err
}
