// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgresquery

import (
	"database/sql"
)

type CommitTimestamp struct {
	ID        int64
	Timestamp sql.NullInt64
}

type NodeSetting struct {
	ID          int64
	StorageMode string
	Network     string
}

type NodeSettingsGate struct {
	Name          string
	Value         string
	RecordedEpoch int64
	RecordedSlot  int64
}
