#!/usr/bin/env sh
set -eu

DINGO_BIN="${DINGO_BIN:-dingo}"

export CARDANO_NETWORK="${CARDANO_NETWORK:-preview}"
export DINGO_STORAGE_MODE="${DINGO_STORAGE_MODE:-api}"
export DINGO_BLOCKFROST_PORT="${DINGO_BLOCKFROST_PORT:-3000}"
export DINGO_UTXORPC_PORT="${DINGO_UTXORPC_PORT:-9090}"
export DINGO_MESH_PORT="${DINGO_MESH_PORT:-8080}"
export DINGO_DATABASE_METADATA_PLUGIN="${DINGO_DATABASE_METADATA_PLUGIN:-sqlite}"
export DINGO_DATABASE_BLOB_PLUGIN="${DINGO_DATABASE_BLOB_PLUGIN:-badger}"

exec "$DINGO_BIN" serve "$@"
