-- Version 1 (v1alpha1) is the schema supported at the database/sql cutover.
-- This file is immutable after release; changes are detected by its checksum.
CREATE TABLE IF NOT EXISTS `commit_timestamp` (`id` integer PRIMARY KEY AUTOINCREMENT,`timestamp` integer);
CREATE TABLE IF NOT EXISTS `node_settings` (`id` integer PRIMARY KEY AUTOINCREMENT,`storage_mode` text NOT NULL,`network` text NOT NULL);
CREATE TABLE IF NOT EXISTS `account` (`staking_key` blob,`credential_tag` integer NOT NULL DEFAULT 0,`pool` blob,`drep` blob,`id` integer PRIMARY KEY AUTOINCREMENT,`added_slot` integer,`created_slot` integer NOT NULL DEFAULT 0,`certificate_id` integer,`reward` text,`drep_type` integer DEFAULT 0,`active` numeric DEFAULT true,`expiration_epoch` integer DEFAULT 0);
CREATE INDEX IF NOT EXISTS `idx_account_expiration_epoch` ON `account`(`expiration_epoch`);
CREATE INDEX IF NOT EXISTS `idx_account_certificate_id` ON `account`(`certificate_id`);
CREATE INDEX IF NOT EXISTS `idx_account_added_slot` ON `account`(`added_slot`);
CREATE INDEX IF NOT EXISTS `idx_account_drep` ON `account`(`drep`);
CREATE INDEX IF NOT EXISTS `idx_account_pool` ON `account`(`pool`);
CREATE INDEX IF NOT EXISTS `idx_account_active_pool_staking_key` ON `account`(`active`,`pool`,`credential_tag`,`staking_key`);
CREATE INDEX IF NOT EXISTS `idx_account_drep_type_active_staking_key` ON `account`(`drep_type`,`active`,`credential_tag`,`staking_key`);
CREATE INDEX IF NOT EXISTS `idx_account_drep_active_staking_key` ON `account`(`drep`,`active`,`credential_tag`,`staking_key`);
CREATE UNIQUE INDEX IF NOT EXISTS `idx_account_credential` ON `account`(`credential_tag`,`staking_key`);
CREATE TABLE IF NOT EXISTS `account_inactivity_activation` (`credential_tag` integer,`staking_key` blob,PRIMARY KEY (`credential_tag`,`staking_key`));
CREATE INDEX IF NOT EXISTS `idx_account_inactivity_activation_staking_key` ON `account_inactivity_activation`(`staking_key`);
CREATE TABLE IF NOT EXISTS `account_reward_delta` (`staking_key` blob NOT NULL,`credential_tag` integer NOT NULL DEFAULT 0,`tx_hash` blob NOT NULL,`amount` text NOT NULL,`previous_reward` text,`id` integer PRIMARY KEY AUTOINCREMENT,`added_slot` integer NOT NULL,`withdrawal` numeric NOT NULL DEFAULT false);
CREATE INDEX IF NOT EXISTS `idx_account_reward_delta_withdrawal` ON `account_reward_delta`(`withdrawal`);
CREATE INDEX IF NOT EXISTS `idx_account_reward_delta_added_slot` ON `account_reward_delta`(`added_slot`);
CREATE INDEX IF NOT EXISTS `idx_account_reward_delta_tx_hash` ON `account_reward_delta`(`tx_hash`);
CREATE UNIQUE INDEX IF NOT EXISTS `idx_account_reward_delta_w_tx_s_slot` ON `account_reward_delta`(`withdrawal`,`tx_hash`,`credential_tag`,`staking_key`,`added_slot`);
CREATE INDEX IF NOT EXISTS `idx_account_reward_delta_credential` ON `account_reward_delta`(`credential_tag`,`staking_key`);
CREATE TABLE IF NOT EXISTS `account_withdrawal_witness` (`staking_key` blob NOT NULL,`credential_tag` integer NOT NULL DEFAULT 0,`tx_hash` blob NOT NULL,`id` integer PRIMARY KEY AUTOINCREMENT,`added_slot` integer NOT NULL);
CREATE INDEX IF NOT EXISTS `idx_account_withdrawal_witness_added_slot` ON `account_withdrawal_witness`(`added_slot`);
CREATE INDEX IF NOT EXISTS `idx_account_withdrawal_witness_credential_slot` ON `account_withdrawal_witness`(`staking_key`,`credential_tag`,`added_slot`);
CREATE UNIQUE INDEX IF NOT EXISTS `idx_account_withdrawal_witness` ON `account_withdrawal_witness`(`tx_hash`,`credential_tag`,`staking_key`);
CREATE TABLE IF NOT EXISTS `address_transaction` (`id` integer PRIMARY KEY AUTOINCREMENT,`payment_key` blob,`staking_key` blob,`credential_tag` integer NOT NULL DEFAULT 0,`transaction_id` integer,`slot` integer,`tx_index` integer);
CREATE INDEX IF NOT EXISTS `idx_address_transaction_slot` ON `address_transaction`(`slot`);
CREATE INDEX IF NOT EXISTS `idx_address_transaction_transaction_id` ON `address_transaction`(`transaction_id`);
CREATE INDEX IF NOT EXISTS `idx_addr_tx_stake_position` ON `address_transaction`(`credential_tag`,`staking_key`,`slot`,`tx_index`,`payment_key`);
CREATE INDEX IF NOT EXISTS `idx_addr_tx_payment` ON `address_transaction`(`payment_key`);
CREATE TABLE IF NOT EXISTS `transaction` (`hash` blob,`block_hash` blob,`metadata` blob,`slot` integer,`type` integer,`id` integer PRIMARY KEY AUTOINCREMENT,`fee` text,`collateral_fee` text,`ttl` text,`block_index` integer,`valid` numeric);
CREATE INDEX IF NOT EXISTS `idx_transaction_slot` ON `transaction`(`slot`);
CREATE INDEX IF NOT EXISTS `idx_transaction_block_hash` ON `transaction`(`block_hash`);
CREATE UNIQUE INDEX IF NOT EXISTS `idx_transaction_hash` ON `transaction`(`hash`);
CREATE TABLE IF NOT EXISTS `utxo` (`transaction_id` integer,`collateral_return_for_tx_id` integer,`tx_id` blob,`payment_key` blob,`staking_key` blob,`credential_tag` integer NOT NULL DEFAULT 0,`datum_hash` blob,`spent_at_tx_id` blob,`referenced_by_tx_id` blob,`collateral_by_tx_id` blob,`id` integer PRIMARY KEY AUTOINCREMENT,`added_slot` integer,`deleted_slot` integer,`amount` text,`output_idx` integer,`payment_script` numeric,CONSTRAINT `fk_transaction_collateral_return` FOREIGN KEY (`collateral_return_for_tx_id`) REFERENCES `transaction`(`id`) ON DELETE CASCADE,CONSTRAINT `fk_transaction_outputs` FOREIGN KEY (`transaction_id`) REFERENCES `transaction`(`id`) ON DELETE CASCADE,CONSTRAINT `fk_transaction_collateral` FOREIGN KEY (`collateral_by_tx_id`) REFERENCES `transaction`(`hash`),CONSTRAINT `fk_transaction_inputs` FOREIGN KEY (`spent_at_tx_id`) REFERENCES `transaction`(`hash`),CONSTRAINT `fk_transaction_reference_inputs` FOREIGN KEY (`referenced_by_tx_id`) REFERENCES `transaction`(`hash`));
CREATE INDEX IF NOT EXISTS `idx_utxo_deleted_payment_script` ON `utxo`(`deleted_slot`,`payment_script`,`amount`);
CREATE INDEX IF NOT EXISTS `idx_utxo_added_slot` ON `utxo`(`added_slot`);
CREATE INDEX IF NOT EXISTS `idx_utxo_collateral_by_tx_id` ON `utxo`(`collateral_by_tx_id`);
CREATE INDEX IF NOT EXISTS `idx_utxo_referenced_by_tx_id` ON `utxo`(`referenced_by_tx_id`);
CREATE INDEX IF NOT EXISTS `idx_utxo_spent_at_tx_id` ON `utxo`(`spent_at_tx_id`);
CREATE INDEX IF NOT EXISTS `idx_utxo_staking_deleted_amount` ON `utxo`(`credential_tag`,`staking_key`,`deleted_slot`,`amount`);
CREATE INDEX IF NOT EXISTS `idx_utxo_deleted_staking_amount` ON `utxo`(`deleted_slot`,`credential_tag`,`staking_key`,`amount`);
CREATE INDEX IF NOT EXISTS `idx_utxo_staking_key` ON `utxo`(`staking_key`);
CREATE INDEX IF NOT EXISTS `idx_utxo_payment_key` ON `utxo`(`payment_key`);
CREATE UNIQUE INDEX IF NOT EXISTS `tx_id_output_idx` ON `utxo`(`tx_id`,`output_idx`);
CREATE UNIQUE INDEX IF NOT EXISTS `idx_utxo_collateral_return_for_tx_id` ON `utxo`(`collateral_return_for_tx_id`);
CREATE INDEX IF NOT EXISTS `idx_utxo_transaction_id` ON `utxo`(`transaction_id`);
CREATE TABLE IF NOT EXISTS `asset` (`name` blob,`name_hex` blob,`policy_id` blob,`fingerprint` blob,`id` integer PRIMARY KEY AUTOINCREMENT,`utxo_id` integer,`amount` text,CONSTRAINT `fk_utxo_assets` FOREIGN KEY (`utxo_id`) REFERENCES `utxo`(`id`) ON DELETE CASCADE);
CREATE INDEX IF NOT EXISTS `idx_asset_amount` ON `asset`(`amount`);
CREATE INDEX IF NOT EXISTS `idx_asset_utxo_id` ON `asset`(`utxo_id`);
CREATE INDEX IF NOT EXISTS `idx_asset_fingerprint` ON `asset`(`fingerprint`);
CREATE INDEX IF NOT EXISTS `idx_asset_policy_id` ON `asset`(`policy_id`);
CREATE INDEX IF NOT EXISTS `idx_asset_name_hex` ON `asset`(`name_hex`);
CREATE UNIQUE INDEX IF NOT EXISTS `idx_asset_unique` ON `asset`(`name`,`policy_id`,`utxo_id`);
CREATE TABLE IF NOT EXISTS `asset_mint_burn` (`id` integer PRIMARY KEY AUTOINCREMENT,`tx_hash` blob,`policy_id` blob,`name` blob,`fingerprint` blob,`slot` integer,`quantity` text,`tx_index` integer);
CREATE INDEX IF NOT EXISTS `idx_asset_mint_burn_slot` ON `asset_mint_burn`(`slot`);
CREATE INDEX IF NOT EXISTS `idx_asset_mint_burn_fingerprint` ON `asset_mint_burn`(`fingerprint`);
CREATE INDEX IF NOT EXISTS `idx_asset_mint_burn_lookup` ON `asset_mint_burn`(`policy_id`,`name`,`slot`);
CREATE UNIQUE INDEX IF NOT EXISTS `idx_asset_mint_burn_unique` ON `asset_mint_burn`(`tx_hash`,`policy_id`,`name`);
CREATE TABLE IF NOT EXISTS `auth_committee_hot` (`cold_credential` blob,`host_credential` blob,`id` integer PRIMARY KEY AUTOINCREMENT,`certificate_id` integer,`added_slot` integer);
CREATE INDEX IF NOT EXISTS `idx_auth_committee_hot_added_slot` ON `auth_committee_hot`(`added_slot`);
CREATE INDEX IF NOT EXISTS `idx_auth_committee_hot_certificate_id` ON `auth_committee_hot`(`certificate_id`);
CREATE INDEX IF NOT EXISTS `idx_auth_committee_hot_hot_credential` ON `auth_committee_hot`(`host_credential`);
CREATE INDEX IF NOT EXISTS `idx_auth_committee_hot_cold_credential` ON `auth_committee_hot`(`cold_credential`);
CREATE TABLE IF NOT EXISTS `backfill_checkpoint` (`id` integer PRIMARY KEY AUTOINCREMENT,`phase` text NOT NULL,`last_slot` integer,`total_slots` integer,`started_at` datetime,`updated_at` datetime,`completed` numeric);
CREATE UNIQUE INDEX IF NOT EXISTS `idx_backfill_checkpoint_phase` ON `backfill_checkpoint`(`phase`);
CREATE TABLE IF NOT EXISTS `block_nonce` (`hash` blob,`nonce` blob,`id` integer PRIMARY KEY AUTOINCREMENT,`slot` integer,`is_checkpoint` numeric);
CREATE UNIQUE INDEX IF NOT EXISTS `hash_slot` ON `block_nonce`(`hash`,`slot`);
CREATE TABLE IF NOT EXISTS `certs` (`block_hash` blob,`id` integer PRIMARY KEY AUTOINCREMENT,`transaction_id` integer,`certificate_id` integer,`slot` integer,`cert_index` integer,`cert_type` integer,CONSTRAINT `fk_transaction_certificates` FOREIGN KEY (`transaction_id`) REFERENCES `transaction`(`id`) ON DELETE CASCADE);
CREATE INDEX IF NOT EXISTS `idx_certs_cert_type` ON `certs`(`cert_type`);
CREATE INDEX IF NOT EXISTS `idx_certs_slot` ON `certs`(`slot`);
CREATE INDEX IF NOT EXISTS `idx_certs_certificate_id` ON `certs`(`certificate_id`);
CREATE UNIQUE INDEX IF NOT EXISTS `uniq_tx_cert` ON `certs`(`transaction_id`,`cert_index`);
CREATE INDEX IF NOT EXISTS `idx_certs_transaction_id` ON `certs`(`transaction_id`);
CREATE INDEX IF NOT EXISTS `idx_certs_block_hash` ON `certs`(`block_hash`);
CREATE TABLE IF NOT EXISTS `committee_member` (`id` integer PRIMARY KEY AUTOINCREMENT,`cold_cred_hash` blob NOT NULL,`expires_epoch` integer NOT NULL,`added_slot` integer NOT NULL,`deleted_slot` integer);
CREATE INDEX IF NOT EXISTS `idx_committee_member_deleted_slot` ON `committee_member`(`deleted_slot`);
CREATE INDEX IF NOT EXISTS `idx_committee_member_added_slot` ON `committee_member`(`added_slot`);
CREATE UNIQUE INDEX IF NOT EXISTS `idx_committee_member_cold_cred_hash` ON `committee_member`(`cold_cred_hash`);
CREATE TABLE IF NOT EXISTS `committee_quorum` (`quorum` text,`id` integer PRIMARY KEY AUTOINCREMENT,`added_slot` integer NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS `idx_committee_quorum_added_slot` ON `committee_quorum`(`added_slot`);
CREATE TABLE IF NOT EXISTS `constitution` (`id` integer PRIMARY KEY AUTOINCREMENT,`anchor_url` text NOT NULL,`anchor_hash` blob NOT NULL,`policy_hash` blob,`added_slot` integer NOT NULL,`deleted_slot` integer);
CREATE INDEX IF NOT EXISTS `idx_constitution_deleted_slot` ON `constitution`(`deleted_slot`);
CREATE UNIQUE INDEX IF NOT EXISTS `idx_constitution_added_slot` ON `constitution`(`added_slot`);
CREATE TABLE IF NOT EXISTS `datum` (`hash` blob NOT NULL,`raw_datum` blob NOT NULL,`id` integer PRIMARY KEY AUTOINCREMENT,`added_slot` integer NOT NULL,CONSTRAINT `uni_datum_hash` UNIQUE (`hash`));
CREATE INDEX IF NOT EXISTS `idx_datum_added_slot` ON `datum`(`added_slot`);
CREATE INDEX IF NOT EXISTS `idx_datum_hash` ON `datum`(`hash`);
CREATE TABLE IF NOT EXISTS `deregistration` (`staking_key` blob,`credential_tag` integer NOT NULL DEFAULT 0,`id` integer PRIMARY KEY AUTOINCREMENT,`certificate_id` integer,`added_slot` integer,`amount` text);
CREATE INDEX IF NOT EXISTS `idx_deregistration_added_slot` ON `deregistration`(`added_slot`);
CREATE INDEX IF NOT EXISTS `idx_deregistration_certificate_id` ON `deregistration`(`certificate_id`);
CREATE INDEX IF NOT EXISTS `idx_deregistration_credential` ON `deregistration`(`credential_tag`,`staking_key`);
CREATE TABLE IF NOT EXISTS `deregistration_drep` (`drep_credential` blob,`certificate_id` integer,`id` integer PRIMARY KEY AUTOINCREMENT,`credential_tag` integer NOT NULL DEFAULT 0,`added_slot` integer,`deposit_amount` text);
CREATE INDEX IF NOT EXISTS `idx_deregistration_drep_added_slot` ON `deregistration_drep`(`added_slot`);
CREATE INDEX IF NOT EXISTS `idx_deregistration_drep_certificate_id` ON `deregistration_drep`(`certificate_id`);
CREATE INDEX IF NOT EXISTS `idx_dereg_drep_credential` ON `deregistration_drep`(`credential_tag`,`drep_credential`);
CREATE TABLE IF NOT EXISTS `drep` (`anchor_url` text,`credential` blob,`anchor_hash` blob,`id` integer PRIMARY KEY AUTOINCREMENT,`added_slot` integer,`credential_tag` integer NOT NULL DEFAULT 0,`last_activity_epoch` integer DEFAULT 0,`expiry_epoch` integer DEFAULT 0,`active` numeric DEFAULT true);
CREATE INDEX IF NOT EXISTS `idx_drep_active` ON `drep`(`active`);
CREATE INDEX IF NOT EXISTS `idx_drep_expiry_epoch` ON `drep`(`expiry_epoch`);
CREATE INDEX IF NOT EXISTS `idx_drep_last_activity_epoch` ON `drep`(`last_activity_epoch`);
CREATE INDEX IF NOT EXISTS `idx_drep_added_slot` ON `drep`(`added_slot`);
CREATE UNIQUE INDEX IF NOT EXISTS `idx_drep_credential` ON `drep`(`credential_tag`,`credential`);
CREATE TABLE IF NOT EXISTS `epoch` (`nonce` blob,`evolving_nonce` blob,`candidate_nonce` blob,`last_epoch_block_nonce` blob,`id` integer PRIMARY KEY AUTOINCREMENT,`epoch_id` integer,`start_slot` integer,`era_id` integer,`slot_length` integer,`length_in_slots` integer);
CREATE UNIQUE INDEX IF NOT EXISTS `idx_epoch_epoch_id` ON `epoch`(`epoch_id`);
CREATE TABLE IF NOT EXISTS `epoch_summary` (`id` integer PRIMARY KEY AUTOINCREMENT,`epoch` integer NOT NULL,`total_active_stake` text NOT NULL,`total_pool_count` integer NOT NULL,`total_delegators` integer NOT NULL,`epoch_nonce` blob,`boundary_slot` integer NOT NULL,`snapshot_ready` numeric NOT NULL DEFAULT false);
CREATE UNIQUE INDEX IF NOT EXISTS `idx_epoch_summary_epoch` ON `epoch_summary`(`epoch`);
CREATE TABLE IF NOT EXISTS `genesis_delegation` (`id` integer PRIMARY KEY AUTOINCREMENT,`genesis_hash` blob NOT NULL,`genesis_delegate_hash` blob NOT NULL,`vrf_key_hash` blob NOT NULL,`added_slot` integer NOT NULL,`block_index` integer NOT NULL,`cert_index` integer NOT NULL,`certificate_id` integer);
CREATE UNIQUE INDEX IF NOT EXISTS `idx_genesis_delegation_certificate_id` ON `genesis_delegation`(`certificate_id`);
CREATE INDEX IF NOT EXISTS `idx_genesis_delegation_added_slot` ON `genesis_delegation`(`added_slot`);
CREATE INDEX IF NOT EXISTS `idx_genesis_delegation_genesis_delegate_hash` ON `genesis_delegation`(`genesis_delegate_hash`);
CREATE INDEX IF NOT EXISTS `idx_genesis_delegation_lookup` ON `genesis_delegation`(`genesis_hash`,`added_slot`,`block_index`,`cert_index`);
CREATE TABLE IF NOT EXISTS `governance_proposal` (`id` integer PRIMARY KEY AUTOINCREMENT,`tx_hash` blob NOT NULL,`action_index` integer NOT NULL,`action_type` integer NOT NULL,`proposed_epoch` integer NOT NULL,`expires_epoch` integer NOT NULL,`parent_tx_hash` blob,`parent_action_idx` integer,`enacted_epoch` integer,`enacted_slot` integer,`ratified_epoch` integer,`ratified_slot` integer,`policy_hash` blob,`anchor_url` text NOT NULL,`anchor_hash` blob NOT NULL,`deposit` integer NOT NULL,`return_address` blob NOT NULL,`gov_action_cbor` blob,`expired_epoch` integer,`expired_slot` integer,`added_slot` integer NOT NULL,`deleted_slot` integer);
CREATE INDEX IF NOT EXISTS `idx_governance_proposal_deleted_slot` ON `governance_proposal`(`deleted_slot`);
CREATE INDEX IF NOT EXISTS `idx_governance_proposal_added_slot` ON `governance_proposal`(`added_slot`);
CREATE INDEX IF NOT EXISTS `idx_governance_proposal_expired_slot` ON `governance_proposal`(`expired_slot`);
CREATE INDEX IF NOT EXISTS `idx_governance_proposal_expired_epoch` ON `governance_proposal`(`expired_epoch`);
CREATE INDEX IF NOT EXISTS `idx_governance_proposal_ratified_slot` ON `governance_proposal`(`ratified_slot`);
CREATE INDEX IF NOT EXISTS `idx_governance_proposal_enacted_slot` ON `governance_proposal`(`enacted_slot`);
CREATE INDEX IF NOT EXISTS `idx_gov_proposal_parent` ON `governance_proposal`(`parent_tx_hash`,`parent_action_idx`);
CREATE INDEX IF NOT EXISTS `idx_governance_proposal_expires_epoch` ON `governance_proposal`(`expires_epoch`);
CREATE INDEX IF NOT EXISTS `idx_governance_proposal_proposed_epoch` ON `governance_proposal`(`proposed_epoch`);
CREATE INDEX IF NOT EXISTS `idx_governance_proposal_action_type` ON `governance_proposal`(`action_type`);
CREATE UNIQUE INDEX IF NOT EXISTS `idx_proposal_tx_action` ON `governance_proposal`(`tx_hash`,`action_index`);
CREATE TABLE IF NOT EXISTS `governance_vote` (`id` integer PRIMARY KEY AUTOINCREMENT,`proposal_id` integer NOT NULL,`voter_type` integer NOT NULL,`voter_credential_tag` integer NOT NULL DEFAULT 0,`voter_credential` blob NOT NULL,`vote` integer NOT NULL,`anchor_url` text,`anchor_hash` blob,`added_slot` integer NOT NULL,`vote_updated_slot` integer,`deleted_slot` integer);
CREATE INDEX IF NOT EXISTS `idx_governance_vote_deleted_slot` ON `governance_vote`(`deleted_slot`);
CREATE INDEX IF NOT EXISTS `idx_governance_vote_vote_updated_slot` ON `governance_vote`(`vote_updated_slot`);
CREATE INDEX IF NOT EXISTS `idx_governance_vote_added_slot` ON `governance_vote`(`added_slot`);
CREATE INDEX IF NOT EXISTS `idx_vote_voter` ON `governance_vote`(`voter_type`,`voter_credential_tag`,`voter_credential`);
CREATE UNIQUE INDEX IF NOT EXISTS `idx_vote_unique` ON `governance_vote`(`proposal_id`,`voter_type`,`voter_credential_tag`,`voter_credential`);
CREATE INDEX IF NOT EXISTS `idx_vote_proposal` ON `governance_vote`(`proposal_id`);
CREATE TABLE IF NOT EXISTS `import_checkpoint` (`id` integer PRIMARY KEY AUTOINCREMENT,`import_key` text NOT NULL,`phase` text NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS `idx_import_checkpoint_import_key` ON `import_checkpoint`(`import_key`);
CREATE TABLE IF NOT EXISTS `key_witness` (`vkey` blob,`signature` blob,`public_key` blob,`chain_code` blob,`attributes` blob,`id` integer PRIMARY KEY AUTOINCREMENT,`transaction_id` integer,`type` integer,CONSTRAINT `fk_transaction_key_witnesses` FOREIGN KEY (`transaction_id`) REFERENCES `transaction`(`id`) ON DELETE CASCADE);
CREATE INDEX IF NOT EXISTS `idx_key_witness_type` ON `key_witness`(`type`);
CREATE INDEX IF NOT EXISTS `idx_key_witness_transaction_id` ON `key_witness`(`transaction_id`);
CREATE TABLE IF NOT EXISTS `move_instantaneous_rewards` (`pot` integer,`certificate_id` integer,`id` integer PRIMARY KEY AUTOINCREMENT,`added_slot` integer,`other_pot` text DEFAULT "0");
CREATE INDEX IF NOT EXISTS `idx_move_instantaneous_rewards_added_slot` ON `move_instantaneous_rewards`(`added_slot`);
CREATE INDEX IF NOT EXISTS `idx_move_instantaneous_rewards_certificate_id` ON `move_instantaneous_rewards`(`certificate_id`);
CREATE INDEX IF NOT EXISTS `idx_move_instantaneous_rewards_pot` ON `move_instantaneous_rewards`(`pot`);
CREATE TABLE IF NOT EXISTS `move_instantaneous_rewards_reward` (`credential` blob,`credential_tag` integer NOT NULL DEFAULT 0,`amount` text,`id` integer PRIMARY KEY AUTOINCREMENT,`mir_id` integer,CONSTRAINT `fk_move_instantaneous_rewards_rewards` FOREIGN KEY (`mir_id`) REFERENCES `move_instantaneous_rewards`(`id`) ON DELETE CASCADE);
CREATE INDEX IF NOT EXISTS `idx_move_instantaneous_rewards_reward_mir_id` ON `move_instantaneous_rewards_reward`(`mir_id`);
CREATE INDEX IF NOT EXISTS `idx_mir_reward_credential` ON `move_instantaneous_rewards_reward`(`credential_tag`,`credential`);
CREATE TABLE IF NOT EXISTS `midnight_ariadne_params` (`id` integer PRIMARY KEY AUTOINCREMENT,`epoch` integer NOT NULL,`datum` blob NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS `idx_midnight_ariadne_params_epoch` ON `midnight_ariadne_params`(`epoch`);
CREATE TABLE IF NOT EXISTS `midnight_ariadne_rollbacks` (`id` integer PRIMARY KEY AUTOINCREMENT,`block_number` integer NOT NULL,`epoch` integer NOT NULL,`previous_exists` numeric NOT NULL,`previous_datum` blob);
CREATE UNIQUE INDEX IF NOT EXISTS `idx_midnight_ariadne_rollbacks_block_epoch` ON `midnight_ariadne_rollbacks`(`block_number`,`epoch`);
CREATE TABLE IF NOT EXISTS `midnight_asset_creates` (`id` integer PRIMARY KEY AUTOINCREMENT,`address` blob NOT NULL,`quantity` integer NOT NULL,`tx_hash` blob NOT NULL,`output_index` integer NOT NULL,`block_number` integer NOT NULL,`block_hash` blob NOT NULL,`tx_index` integer NOT NULL,`block_timestamp_ms` integer NOT NULL);
CREATE INDEX IF NOT EXISTS `idx_midnight_asset_creates_block_tx` ON `midnight_asset_creates`(`block_number`,`tx_index`);
CREATE UNIQUE INDEX IF NOT EXISTS `idx_midnight_asset_creates_utxo_lookup` ON `midnight_asset_creates`(`tx_hash`,`output_index`);
CREATE TABLE IF NOT EXISTS `midnight_asset_spends` (`id` integer PRIMARY KEY AUTOINCREMENT,`address` blob NOT NULL,`quantity` integer NOT NULL,`spending_tx_hash` blob NOT NULL,`utxo_tx_hash` blob NOT NULL,`utxo_index` integer NOT NULL,`block_number` integer NOT NULL,`block_hash` blob NOT NULL,`tx_index` integer NOT NULL,`block_timestamp_ms` integer NOT NULL);
CREATE INDEX IF NOT EXISTS `idx_midnight_asset_spends_block_tx` ON `midnight_asset_spends`(`block_number`,`tx_index`);
CREATE UNIQUE INDEX IF NOT EXISTS `idx_midnight_asset_spends_utxo_ref` ON `midnight_asset_spends`(`utxo_tx_hash`,`utxo_index`);
CREATE TABLE IF NOT EXISTS `midnight_committee_candidate_registrations` (`id` integer PRIMARY KEY AUTOINCREMENT,`tx_hash` blob NOT NULL,`output_index` integer NOT NULL,`block_number` integer NOT NULL,`slot_number` integer NOT NULL,`tx_index` integer NOT NULL,`tx_inputs_cbor` blob NOT NULL);
CREATE INDEX IF NOT EXISTS `idx_midnight_committee_candidate_registrations_block_number` ON `midnight_committee_candidate_registrations`(`block_number`);
CREATE UNIQUE INDEX IF NOT EXISTS `idx_midnight_committee_candidate_reg_utxo` ON `midnight_committee_candidate_registrations`(`tx_hash`,`output_index`);
CREATE TABLE IF NOT EXISTS `midnight_deregistrations` (`id` integer PRIMARY KEY AUTOINCREMENT,`full_datum` blob NOT NULL,`tx_hash` blob NOT NULL,`utxo_tx_hash` blob NOT NULL,`utxo_index` integer NOT NULL,`block_number` integer NOT NULL,`block_hash` blob NOT NULL,`tx_index` integer NOT NULL,`block_timestamp_ms` integer NOT NULL);
CREATE INDEX IF NOT EXISTS `idx_midnight_deregistrations_block_tx` ON `midnight_deregistrations`(`block_number`,`tx_index`);
CREATE UNIQUE INDEX IF NOT EXISTS `idx_midnight_deregistrations_utxo_ref` ON `midnight_deregistrations`(`utxo_tx_hash`,`utxo_index`);
CREATE TABLE IF NOT EXISTS `midnight_epoch_candidates` (`id` integer PRIMARY KEY AUTOINCREMENT,`epoch` integer NOT NULL,`block_number` integer NOT NULL DEFAULT 0,`candidates_cbor` blob NOT NULL);
CREATE INDEX IF NOT EXISTS `idx_midnight_epoch_candidates_block_number` ON `midnight_epoch_candidates`(`block_number`);
CREATE UNIQUE INDEX IF NOT EXISTS `idx_midnight_epoch_candidates_epoch` ON `midnight_epoch_candidates`(`epoch`);
CREATE TABLE IF NOT EXISTS `midnight_governance_datums` (`id` integer PRIMARY KEY AUTOINCREMENT,`datum_type` text NOT NULL,`tx_hash` blob NOT NULL,`output_index` integer NOT NULL,`datum` blob NOT NULL,`block_number` integer NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS `idx_midnight_governance_datums_output` ON `midnight_governance_datums`(`datum_type`,`tx_hash`,`output_index`);
CREATE INDEX IF NOT EXISTS `idx_midnight_governance_datums_latest` ON `midnight_governance_datums`(`datum_type`,`block_number` desc);
CREATE TABLE IF NOT EXISTS `midnight_registrations` (`id` integer PRIMARY KEY AUTOINCREMENT,`full_datum` blob NOT NULL,`tx_hash` blob NOT NULL,`output_index` integer NOT NULL,`block_number` integer NOT NULL,`block_hash` blob NOT NULL,`tx_index` integer NOT NULL,`block_timestamp_ms` integer NOT NULL);
CREATE INDEX IF NOT EXISTS `idx_midnight_registrations_block_tx` ON `midnight_registrations`(`block_number`,`tx_index`);
CREATE UNIQUE INDEX IF NOT EXISTS `idx_midnight_registrations_utxo_lookup` ON `midnight_registrations`(`tx_hash`,`output_index`);
CREATE TABLE IF NOT EXISTS `network_donation` (`id` integer PRIMARY KEY AUTOINCREMENT,`slot` integer NOT NULL,`epoch` integer NOT NULL,`amount` integer NOT NULL);
CREATE INDEX IF NOT EXISTS `idx_network_donation_epoch` ON `network_donation`(`epoch`);
CREATE UNIQUE INDEX IF NOT EXISTS `idx_network_donation_slot` ON `network_donation`(`slot`);
CREATE TABLE IF NOT EXISTS `network_state` (`id` integer PRIMARY KEY AUTOINCREMENT,`treasury` text NOT NULL,`reserves` text NOT NULL,`slot` integer NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS `idx_network_state_slot` ON `network_state`(`slot`);
CREATE TABLE IF NOT EXISTS `offchain_metadata` (`fetched_at` datetime,`next_fetch_after` datetime,`created_at` datetime,`updated_at` datetime,`url` text NOT NULL,`source_type` text NOT NULL,`status` text NOT NULL,`content_type` text,`last_error` text,`hash` blob NOT NULL,`body_hash` blob,`content` blob,`id` integer PRIMARY KEY AUTOINCREMENT,`fetch_attempts` integer,`last_http_status` integer);
CREATE UNIQUE INDEX IF NOT EXISTS `idx_offchain_metadata_source_url_hash` ON `offchain_metadata`(`source_type`,`url`,`hash`);
CREATE INDEX IF NOT EXISTS `idx_offchain_metadata_status_next` ON `offchain_metadata`(`status`,`next_fetch_after`);
CREATE TABLE IF NOT EXISTS `pool` (`margin` text,`pool_key_hash` blob,`vrf_key_hash` blob,`reward_account` blob,`latest_op_cert_sequence` integer,`reward_account_credential_tag` integer NOT NULL DEFAULT 0,`id` integer PRIMARY KEY AUTOINCREMENT,`pledge` text,`cost` text);
CREATE UNIQUE INDEX IF NOT EXISTS `idx_pool_pool_key_hash` ON `pool`(`pool_key_hash`);
CREATE TABLE IF NOT EXISTS `pool_opcert_sequence` (`pool_key_hash` blob,`id` integer PRIMARY KEY AUTOINCREMENT,`slot` integer,`sequence` integer);
CREATE INDEX IF NOT EXISTS `idx_pool_opcert_sequence_slot` ON `pool_opcert_sequence`(`slot`);
CREATE UNIQUE INDEX IF NOT EXISTS `idx_pool_opcert_sequence_pool_slot` ON `pool_opcert_sequence`(`pool_key_hash`,`slot`);
CREATE TABLE IF NOT EXISTS `pool_registration` (`margin` text,`metadata_url` text,`vrf_key_hash` blob,`pool_key_hash` blob,`reward_account` blob,`reward_account_credential_tag` integer NOT NULL DEFAULT 0,`metadata_hash` blob,`pledge` text,`cost` text,`certificate_id` integer,`id` integer PRIMARY KEY AUTOINCREMENT,`pool_id` integer,`added_slot` integer,`deposit_amount` text,CONSTRAINT `fk_pool_registration` FOREIGN KEY (`pool_id`) REFERENCES `pool`(`id`) ON DELETE CASCADE);
CREATE UNIQUE INDEX IF NOT EXISTS `idx_pool_reg_pool_slot` ON `pool_registration`(`pool_id`,`added_slot`);
CREATE INDEX IF NOT EXISTS `idx_pool_registration_certificate_id` ON `pool_registration`(`certificate_id`);
CREATE INDEX IF NOT EXISTS `idx_pool_registration_pool_key_hash` ON `pool_registration`(`pool_key_hash`);
CREATE TABLE IF NOT EXISTS `pool_registration_owner` (`key_hash` blob,`id` integer PRIMARY KEY AUTOINCREMENT,`pool_registration_id` integer,`pool_id` integer,CONSTRAINT `fk_pool_owners` FOREIGN KEY (`pool_id`) REFERENCES `pool`(`id`),CONSTRAINT `fk_pool_registration_owners` FOREIGN KEY (`pool_registration_id`) REFERENCES `pool_registration`(`id`) ON DELETE CASCADE);
CREATE INDEX IF NOT EXISTS `idx_pool_registration_owner_pool_id` ON `pool_registration_owner`(`pool_id`);
CREATE INDEX IF NOT EXISTS `idx_pool_registration_owner_pool_registration_id` ON `pool_registration_owner`(`pool_registration_id`);
CREATE TABLE IF NOT EXISTS `pool_registration_relay` (`ipv4` blob,`ipv6` blob,`hostname` text,`id` integer PRIMARY KEY AUTOINCREMENT,`pool_registration_id` integer,`pool_id` integer,`port` integer,CONSTRAINT `fk_pool_relays` FOREIGN KEY (`pool_id`) REFERENCES `pool`(`id`),CONSTRAINT `fk_pool_registration_relays` FOREIGN KEY (`pool_registration_id`) REFERENCES `pool_registration`(`id`) ON DELETE CASCADE);
CREATE INDEX IF NOT EXISTS `idx_pool_registration_relay_pool_id` ON `pool_registration_relay`(`pool_id`);
CREATE INDEX IF NOT EXISTS `idx_pool_registration_relay_pool_registration_id` ON `pool_registration_relay`(`pool_registration_id`);
CREATE TABLE IF NOT EXISTS `pool_retirement` (`pool_key_hash` blob,`certificate_id` integer,`id` integer PRIMARY KEY AUTOINCREMENT,`pool_id` integer,`epoch` integer,`added_slot` integer,CONSTRAINT `fk_pool_retirement` FOREIGN KEY (`pool_id`) REFERENCES `pool`(`id`) ON DELETE CASCADE);
CREATE INDEX IF NOT EXISTS `idx_pool_retirement_added_slot` ON `pool_retirement`(`added_slot`);
CREATE INDEX IF NOT EXISTS `idx_pool_retirement_pool_id` ON `pool_retirement`(`pool_id`);
CREATE INDEX IF NOT EXISTS `idx_pool_retirement_certificate_id` ON `pool_retirement`(`certificate_id`);
CREATE INDEX IF NOT EXISTS `idx_pool_retirement_pool_key_hash` ON `pool_retirement`(`pool_key_hash`);
CREATE TABLE IF NOT EXISTS `pool_stake_snapshot` (`id` integer PRIMARY KEY AUTOINCREMENT,`epoch` integer NOT NULL,`snapshot_type` varchar(4) NOT NULL,`pool_key_hash` blob NOT NULL,`total_stake` text NOT NULL,`stake_denominator` text NOT NULL DEFAULT "0",`delegator_count` integer NOT NULL,`captured_slot` integer NOT NULL,`calculation_version` integer NOT NULL DEFAULT 0,`reward_account_auto_vote` integer NOT NULL DEFAULT 0,`reward_account_auto_vote_resolved` numeric NOT NULL DEFAULT false);
CREATE UNIQUE INDEX IF NOT EXISTS `idx_pool_stake_epoch_pool` ON `pool_stake_snapshot`(`epoch`,`snapshot_type`,`pool_key_hash`);
CREATE TABLE IF NOT EXISTS `pparams` (`cbor` blob,`id` integer PRIMARY KEY AUTOINCREMENT,`added_slot` integer,`epoch` integer,`era_id` integer);
CREATE INDEX IF NOT EXISTS `idx_pparams_added_slot` ON `pparams`(`added_slot`);
CREATE TABLE IF NOT EXISTS `pparam_update` (`genesis_hash` blob,`cbor` blob,`id` integer PRIMARY KEY AUTOINCREMENT,`added_slot` integer,`epoch` integer);
CREATE INDEX IF NOT EXISTS `idx_pparam_update_added_slot` ON `pparam_update`(`added_slot`);
CREATE TABLE IF NOT EXISTS `plutus_data` (`data` blob,`id` integer PRIMARY KEY AUTOINCREMENT,`transaction_id` integer,CONSTRAINT `fk_transaction_plutus_data` FOREIGN KEY (`transaction_id`) REFERENCES `transaction`(`id`) ON DELETE CASCADE);
CREATE INDEX IF NOT EXISTS `idx_plutus_data_transaction_id` ON `plutus_data`(`transaction_id`);
CREATE TABLE IF NOT EXISTS `registration` (`staking_key` blob,`credential_tag` integer NOT NULL DEFAULT 0,`id` integer PRIMARY KEY AUTOINCREMENT,`certificate_id` integer,`added_slot` integer,`deposit_amount` text);
CREATE INDEX IF NOT EXISTS `idx_registration_added_slot` ON `registration`(`added_slot`);
CREATE INDEX IF NOT EXISTS `idx_registration_certificate_id` ON `registration`(`certificate_id`);
CREATE INDEX IF NOT EXISTS `idx_registration_credential` ON `registration`(`credential_tag`,`staking_key`);
CREATE TABLE IF NOT EXISTS `registration_drep` (`anchor_url` text,`drep_credential` blob,`anchor_hash` blob,`certificate_id` integer,`id` integer PRIMARY KEY AUTOINCREMENT,`credential_tag` integer NOT NULL DEFAULT 0,`added_slot` integer,`deposit_amount` text);
CREATE INDEX IF NOT EXISTS `idx_registration_drep_certificate_id` ON `registration_drep`(`certificate_id`);
CREATE UNIQUE INDEX IF NOT EXISTS `idx_drep_reg_cred_slot` ON `registration_drep`(`credential_tag`,`drep_credential`,`added_slot`);
CREATE TABLE IF NOT EXISTS `redeemer` (`data` blob,`id` integer PRIMARY KEY AUTOINCREMENT,`transaction_id` integer,`ex_units_memory` integer,`ex_units_cpu` integer,`index` integer,`tag` integer,CONSTRAINT `fk_transaction_redeemers` FOREIGN KEY (`transaction_id`) REFERENCES `transaction`(`id`) ON DELETE CASCADE);
CREATE INDEX IF NOT EXISTS `idx_redeemer_tag` ON `redeemer`(`tag`);
CREATE INDEX IF NOT EXISTS `idx_redeemer_index` ON `redeemer`(`index`);
CREATE INDEX IF NOT EXISTS `idx_redeemer_transaction_id` ON `redeemer`(`transaction_id`);
CREATE TABLE IF NOT EXISTS `reward_ada_pots` (`id` integer PRIMARY KEY AUTOINCREMENT,`epoch` integer NOT NULL,`treasury` text NOT NULL,`reserves` text NOT NULL,`fees` text NOT NULL,`rewards` text NOT NULL,`captured_slot` integer NOT NULL);
CREATE INDEX IF NOT EXISTS `idx_reward_ada_pots_captured_slot` ON `reward_ada_pots`(`captured_slot`);
CREATE UNIQUE INDEX IF NOT EXISTS `idx_reward_ada_pots_epoch` ON `reward_ada_pots`(`epoch`);
CREATE TABLE IF NOT EXISTS `reward_account_output` (`staking_key` blob NOT NULL,`pool_key_hash` blob NOT NULL,`reward_type` varchar(16) NOT NULL,`id` integer PRIMARY KEY AUTOINCREMENT,`epoch` integer NOT NULL,`credential_tag` integer NOT NULL DEFAULT 0,`amount` text NOT NULL,`spendable` numeric NOT NULL,`guarded` numeric NOT NULL DEFAULT false,`captured_slot` integer NOT NULL,`boundary_slot` integer NOT NULL);
CREATE INDEX IF NOT EXISTS `idx_reward_account_output_boundary_slot` ON `reward_account_output`(`boundary_slot`);
CREATE INDEX IF NOT EXISTS `idx_reward_account_output_captured_slot` ON `reward_account_output`(`captured_slot`);
CREATE UNIQUE INDEX IF NOT EXISTS `idx_reward_account_output_epoch_cred_pool_type` ON `reward_account_output`(`epoch`,`credential_tag`,`staking_key`,`pool_key_hash`,`reward_type`);
CREATE INDEX IF NOT EXISTS `idx_reward_account_output_credential_spendable` ON `reward_account_output`(`credential_tag`,`staking_key`,`spendable`,`epoch`,`pool_key_hash`,`reward_type`);
CREATE INDEX IF NOT EXISTS `idx_reward_account_output_credential_spendable_guarded` ON `reward_account_output`(`credential_tag`,`staking_key`,`spendable`,`guarded`,`epoch`,`pool_key_hash`,`reward_type`);
CREATE TABLE IF NOT EXISTS `reward_live_stake` (`pool_key_hash` blob,`staking_key` blob NOT NULL,`id` integer PRIMARY KEY AUTOINCREMENT,`credential_tag` integer NOT NULL DEFAULT 0,`utxo_stake` text NOT NULL,`reward_stake` text NOT NULL,`total_stake` text NOT NULL,`registered` numeric NOT NULL,`pool_delegation_slot` integer NOT NULL DEFAULT 0,`pool_delegation_block_index` integer NOT NULL DEFAULT 0,`pool_delegation_cert_index` integer NOT NULL DEFAULT 0,`updated_slot` integer NOT NULL,`calculation_version` integer NOT NULL DEFAULT 0);
CREATE INDEX IF NOT EXISTS `idx_reward_live_stake_updated_slot` ON `reward_live_stake`(`updated_slot`);
CREATE UNIQUE INDEX IF NOT EXISTS `idx_reward_live_stake_cred` ON `reward_live_stake`(`credential_tag`,`staking_key`);
CREATE INDEX IF NOT EXISTS `idx_reward_live_stake_pool_order` ON `reward_live_stake`(`pool_key_hash`,`credential_tag`,`staking_key`);
CREATE TABLE IF NOT EXISTS `reward_pool_input` (`margin` text,`pool_key_hash` blob NOT NULL,`reward_account` blob,`blocks_produced` integer,`total_blocks_in_epoch` integer,`id` integer PRIMARY KEY AUTOINCREMENT,`epoch` integer NOT NULL,`pledge` text NOT NULL,`delegated_stake` text NOT NULL,`owner_stake` text NOT NULL DEFAULT "0",`cost` text NOT NULL,`delegator_count` integer NOT NULL,`reward_account_credential_tag` integer NOT NULL DEFAULT 0,`captured_slot` integer NOT NULL,`boundary_slot` integer NOT NULL);
CREATE INDEX IF NOT EXISTS `idx_reward_pool_input_boundary_slot` ON `reward_pool_input`(`boundary_slot`);
CREATE INDEX IF NOT EXISTS `idx_reward_pool_input_captured_slot` ON `reward_pool_input`(`captured_slot`);
CREATE UNIQUE INDEX IF NOT EXISTS `idx_reward_pool_input_epoch_pool` ON `reward_pool_input`(`epoch`,`pool_key_hash`);
CREATE TABLE IF NOT EXISTS `reward_pool_output` (`apparent_performance` text,`pool_key_hash` blob NOT NULL,`id` integer PRIMARY KEY AUTOINCREMENT,`epoch` integer NOT NULL,`optimal_reward` text NOT NULL,`total_reward` text NOT NULL,`leader_reward` text NOT NULL,`member_reward_total` text NOT NULL,`owner_stake` text NOT NULL,`undistributed` text NOT NULL,`unspendable` text NOT NULL,`captured_slot` integer NOT NULL,`boundary_slot` integer NOT NULL);
CREATE INDEX IF NOT EXISTS `idx_reward_pool_output_boundary_slot` ON `reward_pool_output`(`boundary_slot`);
CREATE INDEX IF NOT EXISTS `idx_reward_pool_output_captured_slot` ON `reward_pool_output`(`captured_slot`);
CREATE UNIQUE INDEX IF NOT EXISTS `idx_reward_pool_output_epoch_pool` ON `reward_pool_output`(`epoch`,`pool_key_hash`);
CREATE TABLE IF NOT EXISTS `reward_snapshot` (`id` integer PRIMARY KEY AUTOINCREMENT,`epoch` integer NOT NULL,`snapshot_type` varchar(4) NOT NULL,`total_active_stake` text NOT NULL,`total_pool_count` integer NOT NULL,`total_delegators` integer NOT NULL,`captured_slot` integer NOT NULL,`boundary_slot` integer NOT NULL,`epoch_nonce` blob,`protocol_version` integer NOT NULL,`authoritative` numeric NOT NULL DEFAULT false,`calculation_version` integer NOT NULL DEFAULT 0);
CREATE INDEX IF NOT EXISTS `idx_reward_snapshot_boundary_slot` ON `reward_snapshot`(`boundary_slot`);
CREATE INDEX IF NOT EXISTS `idx_reward_snapshot_captured_slot` ON `reward_snapshot`(`captured_slot`);
CREATE UNIQUE INDEX IF NOT EXISTS `idx_reward_snapshot_epoch_type` ON `reward_snapshot`(`epoch`,`snapshot_type`);
CREATE TABLE IF NOT EXISTS `reward_stake_input` (`pool_key_hash` blob NOT NULL,`staking_key` blob NOT NULL,`id` integer PRIMARY KEY AUTOINCREMENT,`epoch` integer NOT NULL,`credential_tag` integer NOT NULL DEFAULT 0,`stake` text NOT NULL,`owner` numeric NOT NULL DEFAULT false,`registered` numeric NOT NULL,`captured_slot` integer NOT NULL,`boundary_slot` integer NOT NULL);
CREATE INDEX IF NOT EXISTS `idx_reward_stake_input_boundary_slot` ON `reward_stake_input`(`boundary_slot`);
CREATE INDEX IF NOT EXISTS `idx_reward_stake_input_captured_slot` ON `reward_stake_input`(`captured_slot`);
CREATE UNIQUE INDEX IF NOT EXISTS `idx_reward_stake_input_epoch_pool_cred` ON `reward_stake_input`(`epoch`,`pool_key_hash`,`credential_tag`,`staking_key`);
CREATE TABLE IF NOT EXISTS `resign_committee_cold` (`anchor_url` text,`cold_credential` blob,`anchor_hash` blob,`id` integer PRIMARY KEY AUTOINCREMENT,`certificate_id` integer,`added_slot` integer);
CREATE INDEX IF NOT EXISTS `idx_resign_committee_cold_added_slot` ON `resign_committee_cold`(`added_slot`);
CREATE INDEX IF NOT EXISTS `idx_resign_committee_cold_certificate_id` ON `resign_committee_cold`(`certificate_id`);
CREATE INDEX IF NOT EXISTS `idx_resign_committee_cold_cold_credential` ON `resign_committee_cold`(`cold_credential`);
CREATE TABLE IF NOT EXISTS `script` (`hash` blob,`content` blob,`id` integer PRIMARY KEY AUTOINCREMENT,`created_slot` integer,`type` integer,CONSTRAINT `uni_script_hash` UNIQUE (`hash`));
CREATE INDEX IF NOT EXISTS `idx_script_type` ON `script`(`type`);
CREATE INDEX IF NOT EXISTS `idx_script_hash` ON `script`(`hash`);
CREATE TABLE IF NOT EXISTS `stake_delegation` (`staking_key` blob,`credential_tag` integer NOT NULL DEFAULT 0,`pool_key_hash` blob,`certificate_id` integer,`id` integer PRIMARY KEY AUTOINCREMENT,`added_slot` integer);
CREATE INDEX IF NOT EXISTS `idx_stake_delegation_added_slot` ON `stake_delegation`(`added_slot`);
CREATE INDEX IF NOT EXISTS `idx_stake_delegation_certificate_id` ON `stake_delegation`(`certificate_id`);
CREATE INDEX IF NOT EXISTS `idx_stake_delegation_pool_key_hash` ON `stake_delegation`(`pool_key_hash`);
CREATE INDEX IF NOT EXISTS `idx_stake_delegation_credential` ON `stake_delegation`(`credential_tag`,`staking_key`);
CREATE TABLE IF NOT EXISTS `stake_deregistration` (`staking_key` blob,`credential_tag` integer NOT NULL DEFAULT 0,`certificate_id` integer,`id` integer PRIMARY KEY AUTOINCREMENT,`added_slot` integer);
CREATE INDEX IF NOT EXISTS `idx_stake_deregistration_added_slot` ON `stake_deregistration`(`added_slot`);
CREATE INDEX IF NOT EXISTS `idx_stake_deregistration_certificate_id` ON `stake_deregistration`(`certificate_id`);
CREATE INDEX IF NOT EXISTS `idx_stake_deregistration_credential` ON `stake_deregistration`(`credential_tag`,`staking_key`);
CREATE TABLE IF NOT EXISTS `stake_registration` (`staking_key` blob,`credential_tag` integer NOT NULL DEFAULT 0,`certificate_id` integer,`id` integer PRIMARY KEY AUTOINCREMENT,`added_slot` integer,`deposit_amount` text);
CREATE INDEX IF NOT EXISTS `idx_stake_registration_added_slot` ON `stake_registration`(`added_slot`);
CREATE INDEX IF NOT EXISTS `idx_stake_registration_certificate_id` ON `stake_registration`(`certificate_id`);
CREATE INDEX IF NOT EXISTS `idx_stake_registration_credential` ON `stake_registration`(`credential_tag`,`staking_key`);
CREATE TABLE IF NOT EXISTS `stake_registration_delegation` (`staking_key` blob,`credential_tag` integer NOT NULL DEFAULT 0,`pool_key_hash` blob,`certificate_id` integer,`id` integer PRIMARY KEY AUTOINCREMENT,`added_slot` integer,`deposit_amount` text);
CREATE INDEX IF NOT EXISTS `idx_stake_registration_delegation_added_slot` ON `stake_registration_delegation`(`added_slot`);
CREATE INDEX IF NOT EXISTS `idx_stake_registration_delegation_certificate_id` ON `stake_registration_delegation`(`certificate_id`);
CREATE INDEX IF NOT EXISTS `idx_stake_registration_delegation_pool_key_hash` ON `stake_registration_delegation`(`pool_key_hash`);
CREATE INDEX IF NOT EXISTS `idx_stake_registration_delegation_credential` ON `stake_registration_delegation`(`credential_tag`,`staking_key`);
CREATE TABLE IF NOT EXISTS `stake_vote_delegation` (`staking_key` blob,`credential_tag` integer NOT NULL DEFAULT 0,`pool_key_hash` blob,`drep` blob,`drep_type` integer DEFAULT 0,`certificate_id` integer,`id` integer PRIMARY KEY AUTOINCREMENT,`added_slot` integer);
CREATE INDEX IF NOT EXISTS `idx_stake_vote_delegation_added_slot` ON `stake_vote_delegation`(`added_slot`);
CREATE INDEX IF NOT EXISTS `idx_stake_vote_delegation_certificate_id` ON `stake_vote_delegation`(`certificate_id`);
CREATE INDEX IF NOT EXISTS `idx_stake_vote_delegation_drep` ON `stake_vote_delegation`(`drep`);
CREATE INDEX IF NOT EXISTS `idx_stake_vote_delegation_pool_key_hash` ON `stake_vote_delegation`(`pool_key_hash`);
CREATE INDEX IF NOT EXISTS `idx_stake_vote_delegation_credential` ON `stake_vote_delegation`(`credential_tag`,`staking_key`);
CREATE TABLE IF NOT EXISTS `stake_vote_registration_delegation` (`staking_key` blob,`credential_tag` integer NOT NULL DEFAULT 0,`pool_key_hash` blob,`drep` blob,`drep_type` integer DEFAULT 0,`certificate_id` integer,`id` integer PRIMARY KEY AUTOINCREMENT,`added_slot` integer,`deposit_amount` text);
CREATE INDEX IF NOT EXISTS `idx_stake_vote_registration_delegation_added_slot` ON `stake_vote_registration_delegation`(`added_slot`);
CREATE INDEX IF NOT EXISTS `idx_stake_vote_registration_delegation_certificate_id` ON `stake_vote_registration_delegation`(`certificate_id`);
CREATE INDEX IF NOT EXISTS `idx_stake_vote_registration_delegation_drep` ON `stake_vote_registration_delegation`(`drep`);
CREATE INDEX IF NOT EXISTS `idx_stake_vote_registration_delegation_pool_key_hash` ON `stake_vote_registration_delegation`(`pool_key_hash`);
CREATE INDEX IF NOT EXISTS `idx_stake_vote_registration_delegation_credential` ON `stake_vote_registration_delegation`(`credential_tag`,`staking_key`);
CREATE TABLE IF NOT EXISTS `sync_state` (`sync_key` text,`value` text NOT NULL,PRIMARY KEY (`sync_key`));
CREATE TABLE IF NOT EXISTS `tip` (`hash` blob,`id` integer PRIMARY KEY AUTOINCREMENT,`slot` integer,`block_number` integer);
CREATE TABLE IF NOT EXISTS `transaction_metadata_label` (`id` integer PRIMARY KEY AUTOINCREMENT,`transaction_id` integer,`label` text,`slot` integer,`cbor_value` blob,`json_value` text);
CREATE INDEX IF NOT EXISTS `idx_transaction_metadata_label_slot` ON `transaction_metadata_label`(`slot`);
CREATE INDEX IF NOT EXISTS `idx_transaction_metadata_label_label` ON `transaction_metadata_label`(`label`);
CREATE UNIQUE INDEX IF NOT EXISTS `idx_tx_metadata_label_tx_label` ON `transaction_metadata_label`(`transaction_id`,`label`);
CREATE TABLE IF NOT EXISTS `update_drep` (`anchor_url` text,`credential` blob,`anchor_hash` blob,`certificate_id` integer,`id` integer PRIMARY KEY AUTOINCREMENT,`credential_tag` integer NOT NULL DEFAULT 0,`added_slot` integer);
CREATE INDEX IF NOT EXISTS `idx_update_drep_added_slot` ON `update_drep`(`added_slot`);
CREATE INDEX IF NOT EXISTS `idx_update_drep_certificate_id` ON `update_drep`(`certificate_id`);
CREATE INDEX IF NOT EXISTS `idx_update_drep_credential` ON `update_drep`(`credential_tag`,`credential`);
CREATE TABLE IF NOT EXISTS `vote_delegation` (`staking_key` blob,`credential_tag` integer NOT NULL DEFAULT 0,`drep` blob,`drep_type` integer DEFAULT 0,`certificate_id` integer,`id` integer PRIMARY KEY AUTOINCREMENT,`added_slot` integer);
CREATE INDEX IF NOT EXISTS `idx_vote_delegation_added_slot` ON `vote_delegation`(`added_slot`);
CREATE INDEX IF NOT EXISTS `idx_vote_delegation_certificate_id` ON `vote_delegation`(`certificate_id`);
CREATE INDEX IF NOT EXISTS `idx_vote_delegation_drep` ON `vote_delegation`(`drep`);
CREATE INDEX IF NOT EXISTS `idx_vote_delegation_credential` ON `vote_delegation`(`credential_tag`,`staking_key`);
CREATE TABLE IF NOT EXISTS `vote_registration_delegation` (`staking_key` blob,`credential_tag` integer NOT NULL DEFAULT 0,`drep` blob,`drep_type` integer DEFAULT 0,`certificate_id` integer,`id` integer PRIMARY KEY AUTOINCREMENT,`added_slot` integer,`deposit_amount` text);
CREATE INDEX IF NOT EXISTS `idx_vote_registration_delegation_added_slot` ON `vote_registration_delegation`(`added_slot`);
CREATE INDEX IF NOT EXISTS `idx_vote_registration_delegation_certificate_id` ON `vote_registration_delegation`(`certificate_id`);
CREATE INDEX IF NOT EXISTS `idx_vote_registration_delegation_drep` ON `vote_registration_delegation`(`drep`);
CREATE INDEX IF NOT EXISTS `idx_vote_registration_delegation_credential` ON `vote_registration_delegation`(`credential_tag`,`staking_key`);
CREATE TABLE IF NOT EXISTS `witness_scripts` (`script_hash` blob,`id` integer PRIMARY KEY AUTOINCREMENT,`transaction_id` integer,`type` integer,CONSTRAINT `fk_transaction_witness_scripts` FOREIGN KEY (`transaction_id`) REFERENCES `transaction`(`id`) ON DELETE CASCADE);
CREATE INDEX IF NOT EXISTS `idx_witness_scripts_type` ON `witness_scripts`(`type`);
CREATE INDEX IF NOT EXISTS `idx_witness_scripts_transaction_id` ON `witness_scripts`(`transaction_id`);
CREATE INDEX IF NOT EXISTS `idx_witness_scripts_script_hash` ON `witness_scripts`(`script_hash`);
