apiVersion: v1
kind: Service
metadata:
  name: dingo-blockfrost-explorer-blockfrost
  labels:
    app.kubernetes.io/name: dingo
    cardano_network: preview
    cardano_service: dingo
spec:
  type: LoadBalancer
  ports:
    - name: blockfrost
      port: 3000
      targetPort: blockfrost
  selector:
    app.kubernetes.io/name: dingo
    dingo.blinklabs.io/blockfrost-explorer: "true"
    cardano_network: preview
    cardano_service: dingo
