// NOTE:
// This proto definition is intended to be moved into a separate package/crate
// in the future. The goal is to publish it as a reusable dependency so that
// external clients can import and depend on the shared API contract directly.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: midnight/proto/midnight_state.proto

package midnight

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AssetCreatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartBlock    uint32                 `protobuf:"varint,1,opt,name=start_block,json=startBlock,proto3" json:"start_block,omitempty"`
	StartTxIndex  uint32                 `protobuf:"varint,2,opt,name=start_tx_index,json=startTxIndex,proto3" json:"start_tx_index,omitempty"`
	UtxoCapacity  uint32                 `protobuf:"varint,3,opt,name=utxo_capacity,json=utxoCapacity,proto3" json:"utxo_capacity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetCreatesRequest) Reset() {
	*x = AssetCreatesRequest{}
	mi := &file_midnight_proto_midnight_state_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetCreatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetCreatesRequest) ProtoMessage() {}

func (x *AssetCreatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_midnight_proto_midnight_state_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetCreatesRequest.ProtoReflect.Descriptor instead.
func (*AssetCreatesRequest) Descriptor() ([]byte, []int) {
	return file_midnight_proto_midnight_state_proto_rawDescGZIP(), []int{0}
}

func (x *AssetCreatesRequest) GetStartBlock() uint32 {
	if x != nil {
		return x.StartBlock
	}
	return 0
}

func (x *AssetCreatesRequest) GetStartTxIndex() uint32 {
	if x != nil {
		return x.StartTxIndex
	}
	return 0
}

func (x *AssetCreatesRequest) GetUtxoCapacity() uint32 {
	if x != nil {
		return x.UtxoCapacity
	}
	return 0
}

type AssetCreate struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Address                  []byte                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Quantity                 uint64                 `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	TxHash                   []byte                 `protobuf:"bytes,3,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	OutputIndex              uint32                 `protobuf:"varint,4,opt,name=output_index,json=outputIndex,proto3" json:"output_index,omitempty"`
	BlockNumber              uint64                 `protobuf:"varint,5,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	BlockHash                []byte                 `protobuf:"bytes,6,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	TxIndex                  uint32                 `protobuf:"varint,7,opt,name=tx_index,json=txIndex,proto3" json:"tx_index,omitempty"`
	BlockTimestampUnixMillis int64                  `protobuf:"varint,8,opt,name=block_timestamp_unix_millis,json=blockTimestampUnixMillis,proto3" json:"block_timestamp_unix_millis,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *AssetCreate) Reset() {
	*x = AssetCreate{}
	mi := &file_midnight_proto_midnight_state_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetCreate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetCreate) ProtoMessage() {}

func (x *AssetCreate) ProtoReflect() protoreflect.Message {
	mi := &file_midnight_proto_midnight_state_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetCreate.ProtoReflect.Descriptor instead.
func (*AssetCreate) Descriptor() ([]byte, []int) {
	return file_midnight_proto_midnight_state_proto_rawDescGZIP(), []int{1}
}

func (x *AssetCreate) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *AssetCreate) GetQuantity() uint64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *AssetCreate) GetTxHash() []byte {
	if x != nil {
		return x.TxHash
	}
	return nil
}

func (x *AssetCreate) GetOutputIndex() uint32 {
	if x != nil {
		return x.OutputIndex
	}
	return 0
}

func (x *AssetCreate) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *AssetCreate) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

func (x *AssetCreate) GetTxIndex() uint32 {
	if x != nil {
		return x.TxIndex
	}
	return 0
}

func (x *AssetCreate) GetBlockTimestampUnixMillis() int64 {
	if x != nil {
		return x.BlockTimestampUnixMillis
	}
	return 0
}

type AssetCreatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Creates       []*AssetCreate         `protobuf:"bytes,1,rep,name=creates,proto3" json:"creates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetCreatesResponse) Reset() {
	*x = AssetCreatesResponse{}
	mi := &file_midnight_proto_midnight_state_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetCreatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetCreatesResponse) ProtoMessage() {}

func (x *AssetCreatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_midnight_proto_midnight_state_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetCreatesResponse.ProtoReflect.Descriptor instead.
func (*AssetCreatesResponse) Descriptor() ([]byte, []int) {
	return file_midnight_proto_midnight_state_proto_rawDescGZIP(), []int{2}
}

func (x *AssetCreatesResponse) GetCreates() []*AssetCreate {
	if x != nil {
		return x.Creates
	}
	return nil
}

type AssetSpendsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartBlock    uint32                 `protobuf:"varint,1,opt,name=start_block,json=startBlock,proto3" json:"start_block,omitempty"`
	StartTxIndex  uint32                 `protobuf:"varint,2,opt,name=start_tx_index,json=startTxIndex,proto3" json:"start_tx_index,omitempty"`
	UtxoCapacity  uint32                 `protobuf:"varint,3,opt,name=utxo_capacity,json=utxoCapacity,proto3" json:"utxo_capacity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetSpendsRequest) Reset() {
	*x = AssetSpendsRequest{}
	mi := &file_midnight_proto_midnight_state_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetSpendsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetSpendsRequest) ProtoMessage() {}

func (x *AssetSpendsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_midnight_proto_midnight_state_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetSpendsRequest.ProtoReflect.Descriptor instead.
func (*AssetSpendsRequest) Descriptor() ([]byte, []int) {
	return file_midnight_proto_midnight_state_proto_rawDescGZIP(), []int{3}
}

func (x *AssetSpendsRequest) GetStartBlock() uint32 {
	if x != nil {
		return x.StartBlock
	}
	return 0
}

func (x *AssetSpendsRequest) GetStartTxIndex() uint32 {
	if x != nil {
		return x.StartTxIndex
	}
	return 0
}

func (x *AssetSpendsRequest) GetUtxoCapacity() uint32 {
	if x != nil {
		return x.UtxoCapacity
	}
	return 0
}

type AssetSpend struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Address                  []byte                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Quantity                 uint64                 `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	SpendingTxHash           []byte                 `protobuf:"bytes,3,opt,name=spending_tx_hash,json=spendingTxHash,proto3" json:"spending_tx_hash,omitempty"`
	BlockNumber              uint64                 `protobuf:"varint,4,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	BlockHash                []byte                 `protobuf:"bytes,5,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	TxIndex                  uint32                 `protobuf:"varint,6,opt,name=tx_index,json=txIndex,proto3" json:"tx_index,omitempty"`
	UtxoTxHash               []byte                 `protobuf:"bytes,7,opt,name=utxo_tx_hash,json=utxoTxHash,proto3" json:"utxo_tx_hash,omitempty"`
	UtxoIndex                uint32                 `protobuf:"varint,8,opt,name=utxo_index,json=utxoIndex,proto3" json:"utxo_index,omitempty"`
	BlockTimestampUnixMillis int64                  `protobuf:"varint,9,opt,name=block_timestamp_unix_millis,json=blockTimestampUnixMillis,proto3" json:"block_timestamp_unix_millis,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *AssetSpend) Reset() {
	*x = AssetSpend{}
	mi := &file_midnight_proto_midnight_state_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetSpend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetSpend) ProtoMessage() {}

func (x *AssetSpend) ProtoReflect() protoreflect.Message {
	mi := &file_midnight_proto_midnight_state_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetSpend.ProtoReflect.Descriptor instead.
func (*AssetSpend) Descriptor() ([]byte, []int) {
	return file_midnight_proto_midnight_state_proto_rawDescGZIP(), []int{4}
}

func (x *AssetSpend) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *AssetSpend) GetQuantity() uint64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *AssetSpend) GetSpendingTxHash() []byte {
	if x != nil {
		return x.SpendingTxHash
	}
	return nil
}

func (x *AssetSpend) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *AssetSpend) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

func (x *AssetSpend) GetTxIndex() uint32 {
	if x != nil {
		return x.TxIndex
	}
	return 0
}

func (x *AssetSpend) GetUtxoTxHash() []byte {
	if x != nil {
		return x.UtxoTxHash
	}
	return nil
}

func (x *AssetSpend) GetUtxoIndex() uint32 {
	if x != nil {
		return x.UtxoIndex
	}
	return 0
}

func (x *AssetSpend) GetBlockTimestampUnixMillis() int64 {
	if x != nil {
		return x.BlockTimestampUnixMillis
	}
	return 0
}

type AssetSpendsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spends        []*AssetSpend          `protobuf:"bytes,1,rep,name=spends,proto3" json:"spends,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetSpendsResponse) Reset() {
	*x = AssetSpendsResponse{}
	mi := &file_midnight_proto_midnight_state_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetSpendsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetSpendsResponse) ProtoMessage() {}

func (x *AssetSpendsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_midnight_proto_midnight_state_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetSpendsResponse.ProtoReflect.Descriptor instead.
func (*AssetSpendsResponse) Descriptor() ([]byte, []int) {
	return file_midnight_proto_midnight_state_proto_rawDescGZIP(), []int{5}
}

func (x *AssetSpendsResponse) GetSpends() []*AssetSpend {
	if x != nil {
		return x.Spends
	}
	return nil
}

type RegistrationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartBlock    uint32                 `protobuf:"varint,1,opt,name=start_block,json=startBlock,proto3" json:"start_block,omitempty"`
	StartTxIndex  uint32                 `protobuf:"varint,2,opt,name=start_tx_index,json=startTxIndex,proto3" json:"start_tx_index,omitempty"`
	UtxoCapacity  uint32                 `protobuf:"varint,3,opt,name=utxo_capacity,json=utxoCapacity,proto3" json:"utxo_capacity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistrationsRequest) Reset() {
	*x = RegistrationsRequest{}
	mi := &file_midnight_proto_midnight_state_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationsRequest) ProtoMessage() {}

func (x *RegistrationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_midnight_proto_midnight_state_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationsRequest.ProtoReflect.Descriptor instead.
func (*RegistrationsRequest) Descriptor() ([]byte, []int) {
	return file_midnight_proto_midnight_state_proto_rawDescGZIP(), []int{6}
}

func (x *RegistrationsRequest) GetStartBlock() uint32 {
	if x != nil {
		return x.StartBlock
	}
	return 0
}

func (x *RegistrationsRequest) GetStartTxIndex() uint32 {
	if x != nil {
		return x.StartTxIndex
	}
	return 0
}

func (x *RegistrationsRequest) GetUtxoCapacity() uint32 {
	if x != nil {
		return x.UtxoCapacity
	}
	return 0
}

type Registration struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	FullDatum                []byte                 `protobuf:"bytes,1,opt,name=full_datum,json=fullDatum,proto3" json:"full_datum,omitempty"`
	TxHash                   []byte                 `protobuf:"bytes,2,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	OutputIndex              uint32                 `protobuf:"varint,3,opt,name=output_index,json=outputIndex,proto3" json:"output_index,omitempty"`
	BlockNumber              uint64                 `protobuf:"varint,4,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	BlockHash                []byte                 `protobuf:"bytes,5,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	TxIndex                  uint32                 `protobuf:"varint,6,opt,name=tx_index,json=txIndex,proto3" json:"tx_index,omitempty"`
	BlockTimestampUnixMillis int64                  `protobuf:"varint,7,opt,name=block_timestamp_unix_millis,json=blockTimestampUnixMillis,proto3" json:"block_timestamp_unix_millis,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *Registration) Reset() {
	*x = Registration{}
	mi := &file_midnight_proto_midnight_state_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Registration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Registration) ProtoMessage() {}

func (x *Registration) ProtoReflect() protoreflect.Message {
	mi := &file_midnight_proto_midnight_state_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Registration.ProtoReflect.Descriptor instead.
func (*Registration) Descriptor() ([]byte, []int) {
	return file_midnight_proto_midnight_state_proto_rawDescGZIP(), []int{7}
}

func (x *Registration) GetFullDatum() []byte {
	if x != nil {
		return x.FullDatum
	}
	return nil
}

func (x *Registration) GetTxHash() []byte {
	if x != nil {
		return x.TxHash
	}
	return nil
}

func (x *Registration) GetOutputIndex() uint32 {
	if x != nil {
		return x.OutputIndex
	}
	return 0
}

func (x *Registration) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *Registration) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

func (x *Registration) GetTxIndex() uint32 {
	if x != nil {
		return x.TxIndex
	}
	return 0
}

func (x *Registration) GetBlockTimestampUnixMillis() int64 {
	if x != nil {
		return x.BlockTimestampUnixMillis
	}
	return 0
}

type RegistrationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Registrations []*Registration        `protobuf:"bytes,1,rep,name=registrations,proto3" json:"registrations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistrationsResponse) Reset() {
	*x = RegistrationsResponse{}
	mi := &file_midnight_proto_midnight_state_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationsResponse) ProtoMessage() {}

func (x *RegistrationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_midnight_proto_midnight_state_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationsResponse.ProtoReflect.Descriptor instead.
func (*RegistrationsResponse) Descriptor() ([]byte, []int) {
	return file_midnight_proto_midnight_state_proto_rawDescGZIP(), []int{8}
}

func (x *RegistrationsResponse) GetRegistrations() []*Registration {
	if x != nil {
		return x.Registrations
	}
	return nil
}

type DeregistrationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartBlock    uint32                 `protobuf:"varint,1,opt,name=start_block,json=startBlock,proto3" json:"start_block,omitempty"`
	StartTxIndex  uint32                 `protobuf:"varint,2,opt,name=start_tx_index,json=startTxIndex,proto3" json:"start_tx_index,omitempty"`
	UtxoCapacity  uint32                 `protobuf:"varint,3,opt,name=utxo_capacity,json=utxoCapacity,proto3" json:"utxo_capacity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregistrationsRequest) Reset() {
	*x = DeregistrationsRequest{}
	mi := &file_midnight_proto_midnight_state_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregistrationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregistrationsRequest) ProtoMessage() {}

func (x *DeregistrationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_midnight_proto_midnight_state_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregistrationsRequest.ProtoReflect.Descriptor instead.
func (*DeregistrationsRequest) Descriptor() ([]byte, []int) {
	return file_midnight_proto_midnight_state_proto_rawDescGZIP(), []int{9}
}

func (x *DeregistrationsRequest) GetStartBlock() uint32 {
	if x != nil {
		return x.StartBlock
	}
	return 0
}

func (x *DeregistrationsRequest) GetStartTxIndex() uint32 {
	if x != nil {
		return x.StartTxIndex
	}
	return 0
}

func (x *DeregistrationsRequest) GetUtxoCapacity() uint32 {
	if x != nil {
		return x.UtxoCapacity
	}
	return 0
}

type Deregistration struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	FullDatum                []byte                 `protobuf:"bytes,1,opt,name=full_datum,json=fullDatum,proto3" json:"full_datum,omitempty"`
	TxHash                   []byte                 `protobuf:"bytes,2,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	BlockNumber              uint64                 `protobuf:"varint,3,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	BlockHash                []byte                 `protobuf:"bytes,4,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	TxIndex                  uint32                 `protobuf:"varint,5,opt,name=tx_index,json=txIndex,proto3" json:"tx_index,omitempty"`
	UtxoTxHash               []byte                 `protobuf:"bytes,6,opt,name=utxo_tx_hash,json=utxoTxHash,proto3" json:"utxo_tx_hash,omitempty"`
	UtxoIndex                uint32                 `protobuf:"varint,7,opt,name=utxo_index,json=utxoIndex,proto3" json:"utxo_index,omitempty"`
	BlockTimestampUnixMillis int64                  `protobuf:"varint,8,opt,name=block_timestamp_unix_millis,json=blockTimestampUnixMillis,proto3" json:"block_timestamp_unix_millis,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *Deregistration) Reset() {
	*x = Deregistration{}
	mi := &file_midnight_proto_midnight_state_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Deregistration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deregistration) ProtoMessage() {}

func (x *Deregistration) ProtoReflect() protoreflect.Message {
	mi := &file_midnight_proto_midnight_state_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deregistration.ProtoReflect.Descriptor instead.
func (*Deregistration) Descriptor() ([]byte, []int) {
	return file_midnight_proto_midnight_state_proto_rawDescGZIP(), []int{10}
}

func (x *Deregistration) GetFullDatum() []byte {
	if x != nil {
		return x.FullDatum
	}
	return nil
}

func (x *Deregistration) GetTxHash() []byte {
	if x != nil {
		return x.TxHash
	}
	return nil
}

func (x *Deregistration) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *Deregistration) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

func (x *Deregistration) GetTxIndex() uint32 {
	if x != nil {
		return x.TxIndex
	}
	return 0
}

func (x *Deregistration) GetUtxoTxHash() []byte {
	if x != nil {
		return x.UtxoTxHash
	}
	return nil
}

func (x *Deregistration) GetUtxoIndex() uint32 {
	if x != nil {
		return x.UtxoIndex
	}
	return 0
}

func (x *Deregistration) GetBlockTimestampUnixMillis() int64 {
	if x != nil {
		return x.BlockTimestampUnixMillis
	}
	return 0
}

type DeregistrationsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Deregistrations []*Deregistration      `protobuf:"bytes,1,rep,name=deregistrations,proto3" json:"deregistrations,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeregistrationsResponse) Reset() {
	*x = DeregistrationsResponse{}
	mi := &file_midnight_proto_midnight_state_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregistrationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregistrationsResponse) ProtoMessage() {}

func (x *DeregistrationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_midnight_proto_midnight_state_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregistrationsResponse.ProtoReflect.Descriptor instead.
func (*DeregistrationsResponse) Descriptor() ([]byte, []int) {
	return file_midnight_proto_midnight_state_proto_rawDescGZIP(), []int{11}
}

func (x *DeregistrationsResponse) GetDeregistrations() []*Deregistration {
	if x != nil {
		return x.Deregistrations
	}
	return nil
}

type TechnicalCommitteeDatumRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockNumber   uint64                 `protobuf:"varint,1,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TechnicalCommitteeDatumRequest) Reset() {
	*x = TechnicalCommitteeDatumRequest{}
	mi := &file_midnight_proto_midnight_state_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TechnicalCommitteeDatumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TechnicalCommitteeDatumRequest) ProtoMessage() {}

func (x *TechnicalCommitteeDatumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_midnight_proto_midnight_state_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TechnicalCommitteeDatumRequest.ProtoReflect.Descriptor instead.
func (*TechnicalCommitteeDatumRequest) Descriptor() ([]byte, []int) {
	return file_midnight_proto_midnight_state_proto_rawDescGZIP(), []int{12}
}

func (x *TechnicalCommitteeDatumRequest) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

type TechnicalCommitteeDatumResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SourceBlockNumber uint64                 `protobuf:"varint,1,opt,name=source_block_number,json=sourceBlockNumber,proto3" json:"source_block_number,omitempty"`
	Datum             []byte                 `protobuf:"bytes,2,opt,name=datum,proto3" json:"datum,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TechnicalCommitteeDatumResponse) Reset() {
	*x = TechnicalCommitteeDatumResponse{}
	mi := &file_midnight_proto_midnight_state_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TechnicalCommitteeDatumResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TechnicalCommitteeDatumResponse) ProtoMessage() {}

func (x *TechnicalCommitteeDatumResponse) ProtoReflect() protoreflect.Message {
	mi := &file_midnight_proto_midnight_state_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TechnicalCommitteeDatumResponse.ProtoReflect.Descriptor instead.
func (*TechnicalCommitteeDatumResponse) Descriptor() ([]byte, []int) {
	return file_midnight_proto_midnight_state_proto_rawDescGZIP(), []int{13}
}

func (x *TechnicalCommitteeDatumResponse) GetSourceBlockNumber() uint64 {
	if x != nil {
		return x.SourceBlockNumber
	}
	return 0
}

func (x *TechnicalCommitteeDatumResponse) GetDatum() []byte {
	if x != nil {
		return x.Datum
	}
	return nil
}

type CouncilDatumRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockNumber   uint64                 `protobuf:"varint,1,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CouncilDatumRequest) Reset() {
	*x = CouncilDatumRequest{}
	mi := &file_midnight_proto_midnight_state_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CouncilDatumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CouncilDatumRequest) ProtoMessage() {}

func (x *CouncilDatumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_midnight_proto_midnight_state_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CouncilDatumRequest.ProtoReflect.Descriptor instead.
func (*CouncilDatumRequest) Descriptor() ([]byte, []int) {
	return file_midnight_proto_midnight_state_proto_rawDescGZIP(), []int{14}
}

func (x *CouncilDatumRequest) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

type CouncilDatumResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SourceBlockNumber uint64                 `protobuf:"varint,1,opt,name=source_block_number,json=sourceBlockNumber,proto3" json:"source_block_number,omitempty"`
	Datum             []byte                 `protobuf:"bytes,2,opt,name=datum,proto3" json:"datum,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CouncilDatumResponse) Reset() {
	*x = CouncilDatumResponse{}
	mi := &file_midnight_proto_midnight_state_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CouncilDatumResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CouncilDatumResponse) ProtoMessage() {}

func (x *CouncilDatumResponse) ProtoReflect() protoreflect.Message {
	mi := &file_midnight_proto_midnight_state_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CouncilDatumResponse.ProtoReflect.Descriptor instead.
func (*CouncilDatumResponse) Descriptor() ([]byte, []int) {
	return file_midnight_proto_midnight_state_proto_rawDescGZIP(), []int{15}
}

func (x *CouncilDatumResponse) GetSourceBlockNumber() uint64 {
	if x != nil {
		return x.SourceBlockNumber
	}
	return 0
}

func (x *CouncilDatumResponse) GetDatum() []byte {
	if x != nil {
		return x.Datum
	}
	return nil
}

type AriadneParametersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Epoch         uint64                 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AriadneParametersRequest) Reset() {
	*x = AriadneParametersRequest{}
	mi := &file_midnight_proto_midnight_state_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AriadneParametersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AriadneParametersRequest) ProtoMessage() {}

func (x *AriadneParametersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_midnight_proto_midnight_state_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AriadneParametersRequest.ProtoReflect.Descriptor instead.
func (*AriadneParametersRequest) Descriptor() ([]byte, []int) {
	return file_midnight_proto_midnight_state_proto_rawDescGZIP(), []int{16}
}

func (x *AriadneParametersRequest) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

type AriadneParametersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceEpoch   uint64                 `protobuf:"varint,1,opt,name=source_epoch,json=sourceEpoch,proto3" json:"source_epoch,omitempty"`
	Datum         []byte                 `protobuf:"bytes,2,opt,name=datum,proto3" json:"datum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AriadneParametersResponse) Reset() {
	*x = AriadneParametersResponse{}
	mi := &file_midnight_proto_midnight_state_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AriadneParametersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AriadneParametersResponse) ProtoMessage() {}

func (x *AriadneParametersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_midnight_proto_midnight_state_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AriadneParametersResponse.ProtoReflect.Descriptor instead.
func (*AriadneParametersResponse) Descriptor() ([]byte, []int) {
	return file_midnight_proto_midnight_state_proto_rawDescGZIP(), []int{17}
}

func (x *AriadneParametersResponse) GetSourceEpoch() uint64 {
	if x != nil {
		return x.SourceEpoch
	}
	return 0
}

func (x *AriadneParametersResponse) GetDatum() []byte {
	if x != nil {
		return x.Datum
	}
	return nil
}

type EpochNonceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Epoch         uint64                 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EpochNonceRequest) Reset() {
	*x = EpochNonceRequest{}
	mi := &file_midnight_proto_midnight_state_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EpochNonceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EpochNonceRequest) ProtoMessage() {}

func (x *EpochNonceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_midnight_proto_midnight_state_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EpochNonceRequest.ProtoReflect.Descriptor instead.
func (*EpochNonceRequest) Descriptor() ([]byte, []int) {
	return file_midnight_proto_midnight_state_proto_rawDescGZIP(), []int{18}
}

func (x *EpochNonceRequest) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

type EpochNonceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         []byte                 `protobuf:"bytes,1,opt,name=nonce,proto3,oneof" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EpochNonceResponse) Reset() {
	*x = EpochNonceResponse{}
	mi := &file_midnight_proto_midnight_state_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EpochNonceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EpochNonceResponse) ProtoMessage() {}

func (x *EpochNonceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_midnight_proto_midnight_state_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EpochNonceResponse.ProtoReflect.Descriptor instead.
func (*EpochNonceResponse) Descriptor() ([]byte, []int) {
	return file_midnight_proto_midnight_state_proto_rawDescGZIP(), []int{19}
}

func (x *EpochNonceResponse) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

type EpochCandidatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Epoch         uint64                 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EpochCandidatesRequest) Reset() {
	*x = EpochCandidatesRequest{}
	mi := &file_midnight_proto_midnight_state_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EpochCandidatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EpochCandidatesRequest) ProtoMessage() {}

func (x *EpochCandidatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_midnight_proto_midnight_state_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EpochCandidatesRequest.ProtoReflect.Descriptor instead.
func (*EpochCandidatesRequest) Descriptor() ([]byte, []int) {
	return file_midnight_proto_midnight_state_proto_rawDescGZIP(), []int{20}
}

func (x *EpochCandidatesRequest) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

type UtxoId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxHash        []byte                 `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	Index         uint32                 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UtxoId) Reset() {
	*x = UtxoId{}
	mi := &file_midnight_proto_midnight_state_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UtxoId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UtxoId) ProtoMessage() {}

func (x *UtxoId) ProtoReflect() protoreflect.Message {
	mi := &file_midnight_proto_midnight_state_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UtxoId.ProtoReflect.Descriptor instead.
func (*UtxoId) Descriptor() ([]byte, []int) {
	return file_midnight_proto_midnight_state_proto_rawDescGZIP(), []int{21}
}

func (x *UtxoId) GetTxHash() []byte {
	if x != nil {
		return x.TxHash
	}
	return nil
}

func (x *UtxoId) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

type EpochCandidate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FullDatum     []byte                 `protobuf:"bytes,1,opt,name=full_datum,json=fullDatum,proto3" json:"full_datum,omitempty"`
	UtxoTxHash    []byte                 `protobuf:"bytes,2,opt,name=utxo_tx_hash,json=utxoTxHash,proto3" json:"utxo_tx_hash,omitempty"`
	UtxoIndex     uint32                 `protobuf:"varint,3,opt,name=utxo_index,json=utxoIndex,proto3" json:"utxo_index,omitempty"`
	TxInputs      []*UtxoId              `protobuf:"bytes,4,rep,name=tx_inputs,json=txInputs,proto3" json:"tx_inputs,omitempty"`
	EpochNumber   uint64                 `protobuf:"varint,5,opt,name=epoch_number,json=epochNumber,proto3" json:"epoch_number,omitempty"`
	BlockNumber   uint64                 `protobuf:"varint,6,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	SlotNumber    uint64                 `protobuf:"varint,7,opt,name=slot_number,json=slotNumber,proto3" json:"slot_number,omitempty"`
	TxIndex       uint32                 `protobuf:"varint,8,opt,name=tx_index,json=txIndex,proto3" json:"tx_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EpochCandidate) Reset() {
	*x = EpochCandidate{}
	mi := &file_midnight_proto_midnight_state_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EpochCandidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EpochCandidate) ProtoMessage() {}

func (x *EpochCandidate) ProtoReflect() protoreflect.Message {
	mi := &file_midnight_proto_midnight_state_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EpochCandidate.ProtoReflect.Descriptor instead.
func (*EpochCandidate) Descriptor() ([]byte, []int) {
	return file_midnight_proto_midnight_state_proto_rawDescGZIP(), []int{22}
}

func (x *EpochCandidate) GetFullDatum() []byte {
	if x != nil {
		return x.FullDatum
	}
	return nil
}

func (x *EpochCandidate) GetUtxoTxHash() []byte {
	if x != nil {
		return x.UtxoTxHash
	}
	return nil
}

func (x *EpochCandidate) GetUtxoIndex() uint32 {
	if x != nil {
		return x.UtxoIndex
	}
	return 0
}

func (x *EpochCandidate) GetTxInputs() []*UtxoId {
	if x != nil {
		return x.TxInputs
	}
	return nil
}

func (x *EpochCandidate) GetEpochNumber() uint64 {
	if x != nil {
		return x.EpochNumber
	}
	return 0
}

func (x *EpochCandidate) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *EpochCandidate) GetSlotNumber() uint64 {
	if x != nil {
		return x.SlotNumber
	}
	return 0
}

func (x *EpochCandidate) GetTxIndex() uint32 {
	if x != nil {
		return x.TxIndex
	}
	return 0
}

type StakePoolEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PoolHash      []byte                 `protobuf:"bytes,1,opt,name=pool_hash,json=poolHash,proto3" json:"pool_hash,omitempty"`
	Stake         uint64                 `protobuf:"varint,2,opt,name=stake,proto3" json:"stake,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StakePoolEntry) Reset() {
	*x = StakePoolEntry{}
	mi := &file_midnight_proto_midnight_state_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StakePoolEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StakePoolEntry) ProtoMessage() {}

func (x *StakePoolEntry) ProtoReflect() protoreflect.Message {
	mi := &file_midnight_proto_midnight_state_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StakePoolEntry.ProtoReflect.Descriptor instead.
func (*StakePoolEntry) Descriptor() ([]byte, []int) {
	return file_midnight_proto_midnight_state_proto_rawDescGZIP(), []int{23}
}

func (x *StakePoolEntry) GetPoolHash() []byte {
	if x != nil {
		return x.PoolHash
	}
	return nil
}

func (x *StakePoolEntry) GetStake() uint64 {
	if x != nil {
		return x.Stake
	}
	return 0
}

type EpochCandidatesResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Candidates        []*EpochCandidate      `protobuf:"bytes,1,rep,name=candidates,proto3" json:"candidates,omitempty"`
	StakeDistribution []*StakePoolEntry      `protobuf:"bytes,2,rep,name=stake_distribution,json=stakeDistribution,proto3" json:"stake_distribution,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EpochCandidatesResponse) Reset() {
	*x = EpochCandidatesResponse{}
	mi := &file_midnight_proto_midnight_state_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EpochCandidatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EpochCandidatesResponse) ProtoMessage() {}

func (x *EpochCandidatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_midnight_proto_midnight_state_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EpochCandidatesResponse.ProtoReflect.Descriptor instead.
func (*EpochCandidatesResponse) Descriptor() ([]byte, []int) {
	return file_midnight_proto_midnight_state_proto_rawDescGZIP(), []int{24}
}

func (x *EpochCandidatesResponse) GetCandidates() []*EpochCandidate {
	if x != nil {
		return x.Candidates
	}
	return nil
}

func (x *EpochCandidatesResponse) GetStakeDistribution() []*StakePoolEntry {
	if x != nil {
		return x.StakeDistribution
	}
	return nil
}

type UtxoEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxCapacity    uint32                 `protobuf:"varint,1,opt,name=tx_capacity,json=txCapacity,proto3" json:"tx_capacity,omitempty"`
	EndBlockHash  []byte                 `protobuf:"bytes,2,opt,name=end_block_hash,json=endBlockHash,proto3" json:"end_block_hash,omitempty"`
	StartPosition *CardanoPosition       `protobuf:"bytes,3,opt,name=start_position,json=startPosition,proto3" json:"start_position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UtxoEventsRequest) Reset() {
	*x = UtxoEventsRequest{}
	mi := &file_midnight_proto_midnight_state_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UtxoEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UtxoEventsRequest) ProtoMessage() {}

func (x *UtxoEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_midnight_proto_midnight_state_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UtxoEventsRequest.ProtoReflect.Descriptor instead.
func (*UtxoEventsRequest) Descriptor() ([]byte, []int) {
	return file_midnight_proto_midnight_state_proto_rawDescGZIP(), []int{25}
}

func (x *UtxoEventsRequest) GetTxCapacity() uint32 {
	if x != nil {
		return x.TxCapacity
	}
	return 0
}

func (x *UtxoEventsRequest) GetEndBlockHash() []byte {
	if x != nil {
		return x.EndBlockHash
	}
	return nil
}

func (x *UtxoEventsRequest) GetStartPosition() *CardanoPosition {
	if x != nil {
		return x.StartPosition
	}
	return nil
}

type UtxoEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*UtxoEvent_AssetCreate
	//	*UtxoEvent_AssetSpend
	//	*UtxoEvent_Registration
	//	*UtxoEvent_Deregistration
	Kind          isUtxoEvent_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UtxoEvent) Reset() {
	*x = UtxoEvent{}
	mi := &file_midnight_proto_midnight_state_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UtxoEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UtxoEvent) ProtoMessage() {}

func (x *UtxoEvent) ProtoReflect() protoreflect.Message {
	mi := &file_midnight_proto_midnight_state_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UtxoEvent.ProtoReflect.Descriptor instead.
func (*UtxoEvent) Descriptor() ([]byte, []int) {
	return file_midnight_proto_midnight_state_proto_rawDescGZIP(), []int{26}
}

func (x *UtxoEvent) GetKind() isUtxoEvent_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *UtxoEvent) GetAssetCreate() *AssetCreate {
	if x != nil {
		if x, ok := x.Kind.(*UtxoEvent_AssetCreate); ok {
			return x.AssetCreate
		}
	}
	return nil
}

func (x *UtxoEvent) GetAssetSpend() *AssetSpend {
	if x != nil {
		if x, ok := x.Kind.(*UtxoEvent_AssetSpend); ok {
			return x.AssetSpend
		}
	}
	return nil
}

func (x *UtxoEvent) GetRegistration() *Registration {
	if x != nil {
		if x, ok := x.Kind.(*UtxoEvent_Registration); ok {
			return x.Registration
		}
	}
	return nil
}

func (x *UtxoEvent) GetDeregistration() *Deregistration {
	if x != nil {
		if x, ok := x.Kind.(*UtxoEvent_Deregistration); ok {
			return x.Deregistration
		}
	}
	return nil
}

type isUtxoEvent_Kind interface {
	isUtxoEvent_Kind()
}

type UtxoEvent_AssetCreate struct {
	AssetCreate *AssetCreate `protobuf:"bytes,1,opt,name=asset_create,json=assetCreate,proto3,oneof"`
}

type UtxoEvent_AssetSpend struct {
	AssetSpend *AssetSpend `protobuf:"bytes,2,opt,name=asset_spend,json=assetSpend,proto3,oneof"`
}

type UtxoEvent_Registration struct {
	Registration *Registration `protobuf:"bytes,3,opt,name=registration,proto3,oneof"`
}

type UtxoEvent_Deregistration struct {
	Deregistration *Deregistration `protobuf:"bytes,4,opt,name=deregistration,proto3,oneof"`
}

func (*UtxoEvent_AssetCreate) isUtxoEvent_Kind() {}

func (*UtxoEvent_AssetSpend) isUtxoEvent_Kind() {}

func (*UtxoEvent_Registration) isUtxoEvent_Kind() {}

func (*UtxoEvent_Deregistration) isUtxoEvent_Kind() {}

type CardanoPosition struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	BlockHash                []byte                 `protobuf:"bytes,1,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	BlockNumber              uint32                 `protobuf:"varint,2,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	TxIndex                  uint32                 `protobuf:"varint,3,opt,name=tx_index,json=txIndex,proto3" json:"tx_index,omitempty"`
	BlockTimestampUnixMillis int64                  `protobuf:"varint,4,opt,name=block_timestamp_unix_millis,json=blockTimestampUnixMillis,proto3" json:"block_timestamp_unix_millis,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *CardanoPosition) Reset() {
	*x = CardanoPosition{}
	mi := &file_midnight_proto_midnight_state_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardanoPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardanoPosition) ProtoMessage() {}

func (x *CardanoPosition) ProtoReflect() protoreflect.Message {
	mi := &file_midnight_proto_midnight_state_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardanoPosition.ProtoReflect.Descriptor instead.
func (*CardanoPosition) Descriptor() ([]byte, []int) {
	return file_midnight_proto_midnight_state_proto_rawDescGZIP(), []int{27}
}

func (x *CardanoPosition) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

func (x *CardanoPosition) GetBlockNumber() uint32 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *CardanoPosition) GetTxIndex() uint32 {
	if x != nil {
		return x.TxIndex
	}
	return 0
}

func (x *CardanoPosition) GetBlockTimestampUnixMillis() int64 {
	if x != nil {
		return x.BlockTimestampUnixMillis
	}
	return 0
}

type UtxoEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*UtxoEvent           `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	NextPosition  *CardanoPosition       `protobuf:"bytes,2,opt,name=next_position,json=nextPosition,proto3" json:"next_position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UtxoEventsResponse) Reset() {
	*x = UtxoEventsResponse{}
	mi := &file_midnight_proto_midnight_state_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UtxoEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UtxoEventsResponse) ProtoMessage() {}

func (x *UtxoEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_midnight_proto_midnight_state_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UtxoEventsResponse.ProtoReflect.Descriptor instead.
func (*UtxoEventsResponse) Descriptor() ([]byte, []int) {
	return file_midnight_proto_midnight_state_proto_rawDescGZIP(), []int{28}
}

func (x *UtxoEventsResponse) GetEvents() []*UtxoEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *UtxoEventsResponse) GetNextPosition() *CardanoPosition {
	if x != nil {
		return x.NextPosition
	}
	return nil
}

type BlockByHashRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockHash     []byte                 `protobuf:"bytes,1,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockByHashRequest) Reset() {
	*x = BlockByHashRequest{}
	mi := &file_midnight_proto_midnight_state_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockByHashRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockByHashRequest) ProtoMessage() {}

func (x *BlockByHashRequest) ProtoReflect() protoreflect.Message {
	mi := &file_midnight_proto_midnight_state_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockByHashRequest.ProtoReflect.Descriptor instead.
func (*BlockByHashRequest) Descriptor() ([]byte, []int) {
	return file_midnight_proto_midnight_state_proto_rawDescGZIP(), []int{29}
}

func (x *BlockByHashRequest) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

type BlockByHashResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	BlockNumber        uint32                 `protobuf:"varint,1,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	TxCount            uint32                 `protobuf:"varint,2,opt,name=tx_count,json=txCount,proto3" json:"tx_count,omitempty"`
	BlockTimestampUnix int64                  `protobuf:"varint,3,opt,name=block_timestamp_unix,json=blockTimestampUnix,proto3" json:"block_timestamp_unix,omitempty"`
	EpochNumber        uint32                 `protobuf:"varint,4,opt,name=epoch_number,json=epochNumber,proto3" json:"epoch_number,omitempty"`
	SlotNumber         uint64                 `protobuf:"varint,5,opt,name=slot_number,json=slotNumber,proto3" json:"slot_number,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *BlockByHashResponse) Reset() {
	*x = BlockByHashResponse{}
	mi := &file_midnight_proto_midnight_state_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockByHashResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockByHashResponse) ProtoMessage() {}

func (x *BlockByHashResponse) ProtoReflect() protoreflect.Message {
	mi := &file_midnight_proto_midnight_state_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockByHashResponse.ProtoReflect.Descriptor instead.
func (*BlockByHashResponse) Descriptor() ([]byte, []int) {
	return file_midnight_proto_midnight_state_proto_rawDescGZIP(), []int{30}
}

func (x *BlockByHashResponse) GetBlockNumber() uint32 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *BlockByHashResponse) GetTxCount() uint32 {
	if x != nil {
		return x.TxCount
	}
	return 0
}

func (x *BlockByHashResponse) GetBlockTimestampUnix() int64 {
	if x != nil {
		return x.BlockTimestampUnix
	}
	return 0
}

func (x *BlockByHashResponse) GetEpochNumber() uint32 {
	if x != nil {
		return x.EpochNumber
	}
	return 0
}

func (x *BlockByHashResponse) GetSlotNumber() uint64 {
	if x != nil {
		return x.SlotNumber
	}
	return 0
}

type Block struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	BlockNumber        uint32                 `protobuf:"varint,1,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	BlockHash          []byte                 `protobuf:"bytes,2,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	EpochNumber        uint32                 `protobuf:"varint,3,opt,name=epoch_number,json=epochNumber,proto3" json:"epoch_number,omitempty"`
	SlotNumber         uint64                 `protobuf:"varint,4,opt,name=slot_number,json=slotNumber,proto3" json:"slot_number,omitempty"`
	BlockTimestampUnix uint64                 `protobuf:"varint,5,opt,name=block_timestamp_unix,json=blockTimestampUnix,proto3" json:"block_timestamp_unix,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_midnight_proto_midnight_state_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_midnight_proto_midnight_state_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_midnight_proto_midnight_state_proto_rawDescGZIP(), []int{31}
}

func (x *Block) GetBlockNumber() uint32 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *Block) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

func (x *Block) GetEpochNumber() uint32 {
	if x != nil {
		return x.EpochNumber
	}
	return 0
}

func (x *Block) GetSlotNumber() uint64 {
	if x != nil {
		return x.SlotNumber
	}
	return 0
}

func (x *Block) GetBlockTimestampUnix() uint64 {
	if x != nil {
		return x.BlockTimestampUnix
	}
	return 0
}

type LatestStableBlockRequest struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	StabilityOffset         uint32                 `protobuf:"varint,1,opt,name=stability_offset,json=stabilityOffset,proto3" json:"stability_offset,omitempty"`
	AsOfTimestampUnixMillis uint64                 `protobuf:"varint,2,opt,name=as_of_timestamp_unix_millis,json=asOfTimestampUnixMillis,proto3" json:"as_of_timestamp_unix_millis,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *LatestStableBlockRequest) Reset() {
	*x = LatestStableBlockRequest{}
	mi := &file_midnight_proto_midnight_state_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LatestStableBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LatestStableBlockRequest) ProtoMessage() {}

func (x *LatestStableBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_midnight_proto_midnight_state_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LatestStableBlockRequest.ProtoReflect.Descriptor instead.
func (*LatestStableBlockRequest) Descriptor() ([]byte, []int) {
	return file_midnight_proto_midnight_state_proto_rawDescGZIP(), []int{32}
}

func (x *LatestStableBlockRequest) GetStabilityOffset() uint32 {
	if x != nil {
		return x.StabilityOffset
	}
	return 0
}

func (x *LatestStableBlockRequest) GetAsOfTimestampUnixMillis() uint64 {
	if x != nil {
		return x.AsOfTimestampUnixMillis
	}
	return 0
}

type LatestStableBlockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Block         *Block                 `protobuf:"bytes,1,opt,name=block,proto3,oneof" json:"block,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LatestStableBlockResponse) Reset() {
	*x = LatestStableBlockResponse{}
	mi := &file_midnight_proto_midnight_state_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LatestStableBlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LatestStableBlockResponse) ProtoMessage() {}

func (x *LatestStableBlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_midnight_proto_midnight_state_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LatestStableBlockResponse.ProtoReflect.Descriptor instead.
func (*LatestStableBlockResponse) Descriptor() ([]byte, []int) {
	return file_midnight_proto_midnight_state_proto_rawDescGZIP(), []int{33}
}

func (x *LatestStableBlockResponse) GetBlock() *Block {
	if x != nil {
		return x.Block
	}
	return nil
}

type LatestBlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LatestBlockRequest) Reset() {
	*x = LatestBlockRequest{}
	mi := &file_midnight_proto_midnight_state_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LatestBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LatestBlockRequest) ProtoMessage() {}

func (x *LatestBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_midnight_proto_midnight_state_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LatestBlockRequest.ProtoReflect.Descriptor instead.
func (*LatestBlockRequest) Descriptor() ([]byte, []int) {
	return file_midnight_proto_midnight_state_proto_rawDescGZIP(), []int{34}
}

type LatestBlockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Block         *Block                 `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LatestBlockResponse) Reset() {
	*x = LatestBlockResponse{}
	mi := &file_midnight_proto_midnight_state_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LatestBlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LatestBlockResponse) ProtoMessage() {}

func (x *LatestBlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_midnight_proto_midnight_state_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LatestBlockResponse.ProtoReflect.Descriptor instead.
func (*LatestBlockResponse) Descriptor() ([]byte, []int) {
	return file_midnight_proto_midnight_state_proto_rawDescGZIP(), []int{35}
}

func (x *LatestBlockResponse) GetBlock() *Block {
	if x != nil {
		return x.Block
	}
	return nil
}

type StableBlockRequest struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	BlockHash               []byte                 `protobuf:"bytes,1,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	StabilityOffset         uint32                 `protobuf:"varint,2,opt,name=stability_offset,json=stabilityOffset,proto3" json:"stability_offset,omitempty"`
	AsOfTimestampUnixMillis uint64                 `protobuf:"varint,3,opt,name=as_of_timestamp_unix_millis,json=asOfTimestampUnixMillis,proto3" json:"as_of_timestamp_unix_millis,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *StableBlockRequest) Reset() {
	*x = StableBlockRequest{}
	mi := &file_midnight_proto_midnight_state_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StableBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StableBlockRequest) ProtoMessage() {}

func (x *StableBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_midnight_proto_midnight_state_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StableBlockRequest.ProtoReflect.Descriptor instead.
func (*StableBlockRequest) Descriptor() ([]byte, []int) {
	return file_midnight_proto_midnight_state_proto_rawDescGZIP(), []int{36}
}

func (x *StableBlockRequest) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

func (x *StableBlockRequest) GetStabilityOffset() uint32 {
	if x != nil {
		return x.StabilityOffset
	}
	return 0
}

func (x *StableBlockRequest) GetAsOfTimestampUnixMillis() uint64 {
	if x != nil {
		return x.AsOfTimestampUnixMillis
	}
	return 0
}

type StableBlockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Block         *Block                 `protobuf:"bytes,1,opt,name=block,proto3,oneof" json:"block,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StableBlockResponse) Reset() {
	*x = StableBlockResponse{}
	mi := &file_midnight_proto_midnight_state_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StableBlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StableBlockResponse) ProtoMessage() {}

func (x *StableBlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_midnight_proto_midnight_state_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StableBlockResponse.ProtoReflect.Descriptor instead.
func (*StableBlockResponse) Descriptor() ([]byte, []int) {
	return file_midnight_proto_midnight_state_proto_rawDescGZIP(), []int{37}
}

func (x *StableBlockResponse) GetBlock() *Block {
	if x != nil {
		return x.Block
	}
	return nil
}

var File_midnight_proto_midnight_state_proto protoreflect.FileDescriptor

const file_midnight_proto_midnight_state_proto_rawDesc = "" +
	"\n" +
	"#midnight/proto/midnight_state.proto\x12\x0emidnight_state\"\x81\x01\n" +
	"\x13AssetCreatesRequest\x12\x1f\n" +
	"\vstart_block\x18\x01 \x01(\rR\n" +
	"startBlock\x12$\n" +
	"\x0estart_tx_index\x18\x02 \x01(\rR\fstartTxIndex\x12#\n" +
	"\rutxo_capacity\x18\x03 \x01(\rR\futxoCapacity\"\x9b\x02\n" +
	"\vAssetCreate\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\fR\aaddress\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x04R\bquantity\x12\x17\n" +
	"\atx_hash\x18\x03 \x01(\fR\x06txHash\x12!\n" +
	"\foutput_index\x18\x04 \x01(\rR\voutputIndex\x12!\n" +
	"\fblock_number\x18\x05 \x01(\x04R\vblockNumber\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x06 \x01(\fR\tblockHash\x12\x19\n" +
	"\btx_index\x18\a \x01(\rR\atxIndex\x12=\n" +
	"\x1bblock_timestamp_unix_millis\x18\b \x01(\x03R\x18blockTimestampUnixMillis\"M\n" +
	"\x14AssetCreatesResponse\x125\n" +
	"\acreates\x18\x01 \x03(\v2\x1b.midnight_state.AssetCreateR\acreates\"\x80\x01\n" +
	"\x12AssetSpendsRequest\x12\x1f\n" +
	"\vstart_block\x18\x01 \x01(\rR\n" +
	"startBlock\x12$\n" +
	"\x0estart_tx_index\x18\x02 \x01(\rR\fstartTxIndex\x12#\n" +
	"\rutxo_capacity\x18\x03 \x01(\rR\futxoCapacity\"\xc9\x02\n" +
	"\n" +
	"AssetSpend\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\fR\aaddress\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x04R\bquantity\x12(\n" +
	"\x10spending_tx_hash\x18\x03 \x01(\fR\x0espendingTxHash\x12!\n" +
	"\fblock_number\x18\x04 \x01(\x04R\vblockNumber\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x05 \x01(\fR\tblockHash\x12\x19\n" +
	"\btx_index\x18\x06 \x01(\rR\atxIndex\x12 \n" +
	"\futxo_tx_hash\x18\a \x01(\fR\n" +
	"utxoTxHash\x12\x1d\n" +
	"\n" +
	"utxo_index\x18\b \x01(\rR\tutxoIndex\x12=\n" +
	"\x1bblock_timestamp_unix_millis\x18\t \x01(\x03R\x18blockTimestampUnixMillis\"I\n" +
	"\x13AssetSpendsResponse\x122\n" +
	"\x06spends\x18\x01 \x03(\v2\x1a.midnight_state.AssetSpendR\x06spends\"\x82\x01\n" +
	"\x14RegistrationsRequest\x12\x1f\n" +
	"\vstart_block\x18\x01 \x01(\rR\n" +
	"startBlock\x12$\n" +
	"\x0estart_tx_index\x18\x02 \x01(\rR\fstartTxIndex\x12#\n" +
	"\rutxo_capacity\x18\x03 \x01(\rR\futxoCapacity\"\x85\x02\n" +
	"\fRegistration\x12\x1d\n" +
	"\n" +
	"full_datum\x18\x01 \x01(\fR\tfullDatum\x12\x17\n" +
	"\atx_hash\x18\x02 \x01(\fR\x06txHash\x12!\n" +
	"\foutput_index\x18\x03 \x01(\rR\voutputIndex\x12!\n" +
	"\fblock_number\x18\x04 \x01(\x04R\vblockNumber\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x05 \x01(\fR\tblockHash\x12\x19\n" +
	"\btx_index\x18\x06 \x01(\rR\atxIndex\x12=\n" +
	"\x1bblock_timestamp_unix_millis\x18\a \x01(\x03R\x18blockTimestampUnixMillis\"[\n" +
	"\x15RegistrationsResponse\x12B\n" +
	"\rregistrations\x18\x01 \x03(\v2\x1c.midnight_state.RegistrationR\rregistrations\"\x84\x01\n" +
	"\x16DeregistrationsRequest\x12\x1f\n" +
	"\vstart_block\x18\x01 \x01(\rR\n" +
	"startBlock\x12$\n" +
	"\x0estart_tx_index\x18\x02 \x01(\rR\fstartTxIndex\x12#\n" +
	"\rutxo_capacity\x18\x03 \x01(\rR\futxoCapacity\"\xa5\x02\n" +
	"\x0eDeregistration\x12\x1d\n" +
	"\n" +
	"full_datum\x18\x01 \x01(\fR\tfullDatum\x12\x17\n" +
	"\atx_hash\x18\x02 \x01(\fR\x06txHash\x12!\n" +
	"\fblock_number\x18\x03 \x01(\x04R\vblockNumber\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x04 \x01(\fR\tblockHash\x12\x19\n" +
	"\btx_index\x18\x05 \x01(\rR\atxIndex\x12 \n" +
	"\futxo_tx_hash\x18\x06 \x01(\fR\n" +
	"utxoTxHash\x12\x1d\n" +
	"\n" +
	"utxo_index\x18\a \x01(\rR\tutxoIndex\x12=\n" +
	"\x1bblock_timestamp_unix_millis\x18\b \x01(\x03R\x18blockTimestampUnixMillis\"c\n" +
	"\x17DeregistrationsResponse\x12H\n" +
	"\x0fderegistrations\x18\x01 \x03(\v2\x1e.midnight_state.DeregistrationR\x0fderegistrations\"C\n" +
	"\x1eTechnicalCommitteeDatumRequest\x12!\n" +
	"\fblock_number\x18\x01 \x01(\x04R\vblockNumber\"g\n" +
	"\x1fTechnicalCommitteeDatumResponse\x12.\n" +
	"\x13source_block_number\x18\x01 \x01(\x04R\x11sourceBlockNumber\x12\x14\n" +
	"\x05datum\x18\x02 \x01(\fR\x05datum\"8\n" +
	"\x13CouncilDatumRequest\x12!\n" +
	"\fblock_number\x18\x01 \x01(\x04R\vblockNumber\"\\\n" +
	"\x14CouncilDatumResponse\x12.\n" +
	"\x13source_block_number\x18\x01 \x01(\x04R\x11sourceBlockNumber\x12\x14\n" +
	"\x05datum\x18\x02 \x01(\fR\x05datum\"0\n" +
	"\x18AriadneParametersRequest\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x04R\x05epoch\"T\n" +
	"\x19AriadneParametersResponse\x12!\n" +
	"\fsource_epoch\x18\x01 \x01(\x04R\vsourceEpoch\x12\x14\n" +
	"\x05datum\x18\x02 \x01(\fR\x05datum\")\n" +
	"\x11EpochNonceRequest\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x04R\x05epoch\"9\n" +
	"\x12EpochNonceResponse\x12\x19\n" +
	"\x05nonce\x18\x01 \x01(\fH\x00R\x05nonce\x88\x01\x01B\b\n" +
	"\x06_nonce\".\n" +
	"\x16EpochCandidatesRequest\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x04R\x05epoch\"7\n" +
	"\x06UtxoId\x12\x17\n" +
	"\atx_hash\x18\x01 \x01(\fR\x06txHash\x12\x14\n" +
	"\x05index\x18\x02 \x01(\rR\x05index\"\xa7\x02\n" +
	"\x0eEpochCandidate\x12\x1d\n" +
	"\n" +
	"full_datum\x18\x01 \x01(\fR\tfullDatum\x12 \n" +
	"\futxo_tx_hash\x18\x02 \x01(\fR\n" +
	"utxoTxHash\x12\x1d\n" +
	"\n" +
	"utxo_index\x18\x03 \x01(\rR\tutxoIndex\x123\n" +
	"\ttx_inputs\x18\x04 \x03(\v2\x16.midnight_state.UtxoIdR\btxInputs\x12!\n" +
	"\fepoch_number\x18\x05 \x01(\x04R\vepochNumber\x12!\n" +
	"\fblock_number\x18\x06 \x01(\x04R\vblockNumber\x12\x1f\n" +
	"\vslot_number\x18\a \x01(\x04R\n" +
	"slotNumber\x12\x19\n" +
	"\btx_index\x18\b \x01(\rR\atxIndex\"C\n" +
	"\x0eStakePoolEntry\x12\x1b\n" +
	"\tpool_hash\x18\x01 \x01(\fR\bpoolHash\x12\x14\n" +
	"\x05stake\x18\x02 \x01(\x04R\x05stake\"\xa8\x01\n" +
	"\x17EpochCandidatesResponse\x12>\n" +
	"\n" +
	"candidates\x18\x01 \x03(\v2\x1e.midnight_state.EpochCandidateR\n" +
	"candidates\x12M\n" +
	"\x12stake_distribution\x18\x02 \x03(\v2\x1e.midnight_state.StakePoolEntryR\x11stakeDistribution\"\xa2\x01\n" +
	"\x11UtxoEventsRequest\x12\x1f\n" +
	"\vtx_capacity\x18\x01 \x01(\rR\n" +
	"txCapacity\x12$\n" +
	"\x0eend_block_hash\x18\x02 \x01(\fR\fendBlockHash\x12F\n" +
	"\x0estart_position\x18\x03 \x01(\v2\x1f.midnight_state.CardanoPositionR\rstartPosition\"\xa2\x02\n" +
	"\tUtxoEvent\x12@\n" +
	"\fasset_create\x18\x01 \x01(\v2\x1b.midnight_state.AssetCreateH\x00R\vassetCreate\x12=\n" +
	"\vasset_spend\x18\x02 \x01(\v2\x1a.midnight_state.AssetSpendH\x00R\n" +
	"assetSpend\x12B\n" +
	"\fregistration\x18\x03 \x01(\v2\x1c.midnight_state.RegistrationH\x00R\fregistration\x12H\n" +
	"\x0ederegistration\x18\x04 \x01(\v2\x1e.midnight_state.DeregistrationH\x00R\x0ederegistrationB\x06\n" +
	"\x04kind\"\xad\x01\n" +
	"\x0fCardanoPosition\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x01 \x01(\fR\tblockHash\x12!\n" +
	"\fblock_number\x18\x02 \x01(\rR\vblockNumber\x12\x19\n" +
	"\btx_index\x18\x03 \x01(\rR\atxIndex\x12=\n" +
	"\x1bblock_timestamp_unix_millis\x18\x04 \x01(\x03R\x18blockTimestampUnixMillis\"\x8d\x01\n" +
	"\x12UtxoEventsResponse\x121\n" +
	"\x06events\x18\x01 \x03(\v2\x19.midnight_state.UtxoEventR\x06events\x12D\n" +
	"\rnext_position\x18\x02 \x01(\v2\x1f.midnight_state.CardanoPositionR\fnextPosition\"3\n" +
	"\x12BlockByHashRequest\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x01 \x01(\fR\tblockHash\"\xc9\x01\n" +
	"\x13BlockByHashResponse\x12!\n" +
	"\fblock_number\x18\x01 \x01(\rR\vblockNumber\x12\x19\n" +
	"\btx_count\x18\x02 \x01(\rR\atxCount\x120\n" +
	"\x14block_timestamp_unix\x18\x03 \x01(\x03R\x12blockTimestampUnix\x12!\n" +
	"\fepoch_number\x18\x04 \x01(\rR\vepochNumber\x12\x1f\n" +
	"\vslot_number\x18\x05 \x01(\x04R\n" +
	"slotNumber\"\xbf\x01\n" +
	"\x05Block\x12!\n" +
	"\fblock_number\x18\x01 \x01(\rR\vblockNumber\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x02 \x01(\fR\tblockHash\x12!\n" +
	"\fepoch_number\x18\x03 \x01(\rR\vepochNumber\x12\x1f\n" +
	"\vslot_number\x18\x04 \x01(\x04R\n" +
	"slotNumber\x120\n" +
	"\x14block_timestamp_unix\x18\x05 \x01(\x04R\x12blockTimestampUnix\"\x83\x01\n" +
	"\x18LatestStableBlockRequest\x12)\n" +
	"\x10stability_offset\x18\x01 \x01(\rR\x0fstabilityOffset\x12<\n" +
	"\x1bas_of_timestamp_unix_millis\x18\x02 \x01(\x04R\x17asOfTimestampUnixMillis\"W\n" +
	"\x19LatestStableBlockResponse\x120\n" +
	"\x05block\x18\x01 \x01(\v2\x15.midnight_state.BlockH\x00R\x05block\x88\x01\x01B\b\n" +
	"\x06_block\"\x14\n" +
	"\x12LatestBlockRequest\"B\n" +
	"\x13LatestBlockResponse\x12+\n" +
	"\x05block\x18\x01 \x01(\v2\x15.midnight_state.BlockR\x05block\"\x9c\x01\n" +
	"\x12StableBlockRequest\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x01 \x01(\fR\tblockHash\x12)\n" +
	"\x10stability_offset\x18\x02 \x01(\rR\x0fstabilityOffset\x12<\n" +
	"\x1bas_of_timestamp_unix_millis\x18\x03 \x01(\x04R\x17asOfTimestampUnixMillis\"Q\n" +
	"\x13StableBlockResponse\x120\n" +
	"\x05block\x18\x01 \x01(\v2\x15.midnight_state.BlockH\x00R\x05block\x88\x01\x01B\b\n" +
	"\x06_block2\xef\n" +
	"\n" +
	"\rMidnightState\x12\\\n" +
	"\x0fGetAssetCreates\x12#.midnight_state.AssetCreatesRequest\x1a$.midnight_state.AssetCreatesResponse\x12Y\n" +
	"\x0eGetAssetSpends\x12\".midnight_state.AssetSpendsRequest\x1a#.midnight_state.AssetSpendsResponse\x12_\n" +
	"\x10GetRegistrations\x12$.midnight_state.RegistrationsRequest\x1a%.midnight_state.RegistrationsResponse\x12e\n" +
	"\x12GetDeregistrations\x12&.midnight_state.DeregistrationsRequest\x1a'.midnight_state.DeregistrationsResponse\x12}\n" +
	"\x1aGetTechnicalCommitteeDatum\x12..midnight_state.TechnicalCommitteeDatumRequest\x1a/.midnight_state.TechnicalCommitteeDatumResponse\x12\\\n" +
	"\x0fGetCouncilDatum\x12#.midnight_state.CouncilDatumRequest\x1a$.midnight_state.CouncilDatumResponse\x12k\n" +
	"\x14GetAriadneParameters\x12(.midnight_state.AriadneParametersRequest\x1a).midnight_state.AriadneParametersResponse\x12Y\n" +
	"\x0eGetBlockByHash\x12\".midnight_state.BlockByHashRequest\x1a#.midnight_state.BlockByHashResponse\x12V\n" +
	"\rGetUtxoEvents\x12!.midnight_state.UtxoEventsRequest\x1a\".midnight_state.UtxoEventsResponse\x12V\n" +
	"\rGetEpochNonce\x12!.midnight_state.EpochNonceRequest\x1a\".midnight_state.EpochNonceResponse\x12e\n" +
	"\x12GetEpochCandidates\x12&.midnight_state.EpochCandidatesRequest\x1a'.midnight_state.EpochCandidatesResponse\x12Y\n" +
	"\x0eGetStableBlock\x12\".midnight_state.StableBlockRequest\x1a#.midnight_state.StableBlockResponse\x12k\n" +
	"\x14GetLatestStableBlock\x12(.midnight_state.LatestStableBlockRequest\x1a).midnight_state.LatestStableBlockResponse\x12Y\n" +
	"\x0eGetLatestBlock\x12\".midnight_state.LatestBlockRequest\x1a#.midnight_state.LatestBlockResponseb\x06proto3"

var (
	file_midnight_proto_midnight_state_proto_rawDescOnce sync.Once
	file_midnight_proto_midnight_state_proto_rawDescData []byte
)

func file_midnight_proto_midnight_state_proto_rawDescGZIP() []byte {
	file_midnight_proto_midnight_state_proto_rawDescOnce.Do(func() {
		file_midnight_proto_midnight_state_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_midnight_proto_midnight_state_proto_rawDesc), len(file_midnight_proto_midnight_state_proto_rawDesc)))
	})
	return file_midnight_proto_midnight_state_proto_rawDescData
}

var file_midnight_proto_midnight_state_proto_msgTypes = make([]protoimpl.MessageInfo, 38)
var file_midnight_proto_midnight_state_proto_goTypes = []any{
	(*AssetCreatesRequest)(nil),             // 0: midnight_state.AssetCreatesRequest
	(*AssetCreate)(nil),                     // 1: midnight_state.AssetCreate
	(*AssetCreatesResponse)(nil),            // 2: midnight_state.AssetCreatesResponse
	(*AssetSpendsRequest)(nil),              // 3: midnight_state.AssetSpendsRequest
	(*AssetSpend)(nil),                      // 4: midnight_state.AssetSpend
	(*AssetSpendsResponse)(nil),             // 5: midnight_state.AssetSpendsResponse
	(*RegistrationsRequest)(nil),            // 6: midnight_state.RegistrationsRequest
	(*Registration)(nil),                    // 7: midnight_state.Registration
	(*RegistrationsResponse)(nil),           // 8: midnight_state.RegistrationsResponse
	(*DeregistrationsRequest)(nil),          // 9: midnight_state.DeregistrationsRequest
	(*Deregistration)(nil),                  // 10: midnight_state.Deregistration
	(*DeregistrationsResponse)(nil),         // 11: midnight_state.DeregistrationsResponse
	(*TechnicalCommitteeDatumRequest)(nil),  // 12: midnight_state.TechnicalCommitteeDatumRequest
	(*TechnicalCommitteeDatumResponse)(nil), // 13: midnight_state.TechnicalCommitteeDatumResponse
	(*CouncilDatumRequest)(nil),             // 14: midnight_state.CouncilDatumRequest
	(*CouncilDatumResponse)(nil),            // 15: midnight_state.CouncilDatumResponse
	(*AriadneParametersRequest)(nil),        // 16: midnight_state.AriadneParametersRequest
	(*AriadneParametersResponse)(nil),       // 17: midnight_state.AriadneParametersResponse
	(*EpochNonceRequest)(nil),               // 18: midnight_state.EpochNonceRequest
	(*EpochNonceResponse)(nil),              // 19: midnight_state.EpochNonceResponse
	(*EpochCandidatesRequest)(nil),          // 20: midnight_state.EpochCandidatesRequest
	(*UtxoId)(nil),                          // 21: midnight_state.UtxoId
	(*EpochCandidate)(nil),                  // 22: midnight_state.EpochCandidate
	(*StakePoolEntry)(nil),                  // 23: midnight_state.StakePoolEntry
	(*EpochCandidatesResponse)(nil),         // 24: midnight_state.EpochCandidatesResponse
	(*UtxoEventsRequest)(nil),               // 25: midnight_state.UtxoEventsRequest
	(*UtxoEvent)(nil),                       // 26: midnight_state.UtxoEvent
	(*CardanoPosition)(nil),                 // 27: midnight_state.CardanoPosition
	(*UtxoEventsResponse)(nil),              // 28: midnight_state.UtxoEventsResponse
	(*BlockByHashRequest)(nil),              // 29: midnight_state.BlockByHashRequest
	(*BlockByHashResponse)(nil),             // 30: midnight_state.BlockByHashResponse
	(*Block)(nil),                           // 31: midnight_state.Block
	(*LatestStableBlockRequest)(nil),        // 32: midnight_state.LatestStableBlockRequest
	(*LatestStableBlockResponse)(nil),       // 33: midnight_state.LatestStableBlockResponse
	(*LatestBlockRequest)(nil),              // 34: midnight_state.LatestBlockRequest
	(*LatestBlockResponse)(nil),             // 35: midnight_state.LatestBlockResponse
	(*StableBlockRequest)(nil),              // 36: midnight_state.StableBlockRequest
	(*StableBlockResponse)(nil),             // 37: midnight_state.StableBlockResponse
}
var file_midnight_proto_midnight_state_proto_depIdxs = []int32{
	1,  // 0: midnight_state.AssetCreatesResponse.creates:type_name -> midnight_state.AssetCreate
	4,  // 1: midnight_state.AssetSpendsResponse.spends:type_name -> midnight_state.AssetSpend
	7,  // 2: midnight_state.RegistrationsResponse.registrations:type_name -> midnight_state.Registration
	10, // 3: midnight_state.DeregistrationsResponse.deregistrations:type_name -> midnight_state.Deregistration
	21, // 4: midnight_state.EpochCandidate.tx_inputs:type_name -> midnight_state.UtxoId
	22, // 5: midnight_state.EpochCandidatesResponse.candidates:type_name -> midnight_state.EpochCandidate
	23, // 6: midnight_state.EpochCandidatesResponse.stake_distribution:type_name -> midnight_state.StakePoolEntry
	27, // 7: midnight_state.UtxoEventsRequest.start_position:type_name -> midnight_state.CardanoPosition
	1,  // 8: midnight_state.UtxoEvent.asset_create:type_name -> midnight_state.AssetCreate
	4,  // 9: midnight_state.UtxoEvent.asset_spend:type_name -> midnight_state.AssetSpend
	7,  // 10: midnight_state.UtxoEvent.registration:type_name -> midnight_state.Registration
	10, // 11: midnight_state.UtxoEvent.deregistration:type_name -> midnight_state.Deregistration
	26, // 12: midnight_state.UtxoEventsResponse.events:type_name -> midnight_state.UtxoEvent
	27, // 13: midnight_state.UtxoEventsResponse.next_position:type_name -> midnight_state.CardanoPosition
	31, // 14: midnight_state.LatestStableBlockResponse.block:type_name -> midnight_state.Block
	31, // 15: midnight_state.LatestBlockResponse.block:type_name -> midnight_state.Block
	31, // 16: midnight_state.StableBlockResponse.block:type_name -> midnight_state.Block
	0,  // 17: midnight_state.MidnightState.GetAssetCreates:input_type -> midnight_state.AssetCreatesRequest
	3,  // 18: midnight_state.MidnightState.GetAssetSpends:input_type -> midnight_state.AssetSpendsRequest
	6,  // 19: midnight_state.MidnightState.GetRegistrations:input_type -> midnight_state.RegistrationsRequest
	9,  // 20: midnight_state.MidnightState.GetDeregistrations:input_type -> midnight_state.DeregistrationsRequest
	12, // 21: midnight_state.MidnightState.GetTechnicalCommitteeDatum:input_type -> midnight_state.TechnicalCommitteeDatumRequest
	14, // 22: midnight_state.MidnightState.GetCouncilDatum:input_type -> midnight_state.CouncilDatumRequest
	16, // 23: midnight_state.MidnightState.GetAriadneParameters:input_type -> midnight_state.AriadneParametersRequest
	29, // 24: midnight_state.MidnightState.GetBlockByHash:input_type -> midnight_state.BlockByHashRequest
	25, // 25: midnight_state.MidnightState.GetUtxoEvents:input_type -> midnight_state.UtxoEventsRequest
	18, // 26: midnight_state.MidnightState.GetEpochNonce:input_type -> midnight_state.EpochNonceRequest
	20, // 27: midnight_state.MidnightState.GetEpochCandidates:input_type -> midnight_state.EpochCandidatesRequest
	36, // 28: midnight_state.MidnightState.GetStableBlock:input_type -> midnight_state.StableBlockRequest
	32, // 29: midnight_state.MidnightState.GetLatestStableBlock:input_type -> midnight_state.LatestStableBlockRequest
	34, // 30: midnight_state.MidnightState.GetLatestBlock:input_type -> midnight_state.LatestBlockRequest
	2,  // 31: midnight_state.MidnightState.GetAssetCreates:output_type -> midnight_state.AssetCreatesResponse
	5,  // 32: midnight_state.MidnightState.GetAssetSpends:output_type -> midnight_state.AssetSpendsResponse
	8,  // 33: midnight_state.MidnightState.GetRegistrations:output_type -> midnight_state.RegistrationsResponse
	11, // 34: midnight_state.MidnightState.GetDeregistrations:output_type -> midnight_state.DeregistrationsResponse
	13, // 35: midnight_state.MidnightState.GetTechnicalCommitteeDatum:output_type -> midnight_state.TechnicalCommitteeDatumResponse
	15, // 36: midnight_state.MidnightState.GetCouncilDatum:output_type -> midnight_state.CouncilDatumResponse
	17, // 37: midnight_state.MidnightState.GetAriadneParameters:output_type -> midnight_state.AriadneParametersResponse
	30, // 38: midnight_state.MidnightState.GetBlockByHash:output_type -> midnight_state.BlockByHashResponse
	28, // 39: midnight_state.MidnightState.GetUtxoEvents:output_type -> midnight_state.UtxoEventsResponse
	19, // 40: midnight_state.MidnightState.GetEpochNonce:output_type -> midnight_state.EpochNonceResponse
	24, // 41: midnight_state.MidnightState.GetEpochCandidates:output_type -> midnight_state.EpochCandidatesResponse
	37, // 42: midnight_state.MidnightState.GetStableBlock:output_type -> midnight_state.StableBlockResponse
	33, // 43: midnight_state.MidnightState.GetLatestStableBlock:output_type -> midnight_state.LatestStableBlockResponse
	35, // 44: midnight_state.MidnightState.GetLatestBlock:output_type -> midnight_state.LatestBlockResponse
	31, // [31:45] is the sub-list for method output_type
	17, // [17:31] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_midnight_proto_midnight_state_proto_init() }
func file_midnight_proto_midnight_state_proto_init() {
	if File_midnight_proto_midnight_state_proto != nil {
		return
	}
	file_midnight_proto_midnight_state_proto_msgTypes[19].OneofWrappers = []any{}
	file_midnight_proto_midnight_state_proto_msgTypes[26].OneofWrappers = []any{
		(*UtxoEvent_AssetCreate)(nil),
		(*UtxoEvent_AssetSpend)(nil),
		(*UtxoEvent_Registration)(nil),
		(*UtxoEvent_Deregistration)(nil),
	}
	file_midnight_proto_midnight_state_proto_msgTypes[33].OneofWrappers = []any{}
	file_midnight_proto_midnight_state_proto_msgTypes[37].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_midnight_proto_midnight_state_proto_rawDesc), len(file_midnight_proto_midnight_state_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   38,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_midnight_proto_midnight_state_proto_goTypes,
		DependencyIndexes: file_midnight_proto_midnight_state_proto_depIdxs,
		MessageInfos:      file_midnight_proto_midnight_state_proto_msgTypes,
	}.Build()
	File_midnight_proto_midnight_state_proto = out.File
	file_midnight_proto_midnight_state_proto_goTypes = nil
	file_midnight_proto_midnight_state_proto_depIdxs = nil
}
