// NOTE:
// This proto definition is intended to be moved into a separate package/crate
// in the future. The goal is to publish it as a reusable dependency so that
// external clients can import and depend on the shared API contract directly.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.32.1
// source: midnight/proto/midnight_state.proto

package midnight

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MidnightState_GetAssetCreates_FullMethodName            = "/midnight_state.MidnightState/GetAssetCreates"
	MidnightState_GetAssetSpends_FullMethodName             = "/midnight_state.MidnightState/GetAssetSpends"
	MidnightState_GetRegistrations_FullMethodName           = "/midnight_state.MidnightState/GetRegistrations"
	MidnightState_GetDeregistrations_FullMethodName         = "/midnight_state.MidnightState/GetDeregistrations"
	MidnightState_GetTechnicalCommitteeDatum_FullMethodName = "/midnight_state.MidnightState/GetTechnicalCommitteeDatum"
	MidnightState_GetCouncilDatum_FullMethodName            = "/midnight_state.MidnightState/GetCouncilDatum"
	MidnightState_GetAriadneParameters_FullMethodName       = "/midnight_state.MidnightState/GetAriadneParameters"
	MidnightState_GetBlockByHash_FullMethodName             = "/midnight_state.MidnightState/GetBlockByHash"
	MidnightState_GetUtxoEvents_FullMethodName              = "/midnight_state.MidnightState/GetUtxoEvents"
	MidnightState_GetEpochNonce_FullMethodName              = "/midnight_state.MidnightState/GetEpochNonce"
	MidnightState_GetEpochCandidates_FullMethodName         = "/midnight_state.MidnightState/GetEpochCandidates"
	MidnightState_GetStableBlock_FullMethodName             = "/midnight_state.MidnightState/GetStableBlock"
	MidnightState_GetLatestStableBlock_FullMethodName       = "/midnight_state.MidnightState/GetLatestStableBlock"
	MidnightState_GetLatestBlock_FullMethodName             = "/midnight_state.MidnightState/GetLatestBlock"
)

// MidnightStateClient is the client API for MidnightState service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MidnightStateClient interface {
	GetAssetCreates(ctx context.Context, in *AssetCreatesRequest, opts ...grpc.CallOption) (*AssetCreatesResponse, error)
	GetAssetSpends(ctx context.Context, in *AssetSpendsRequest, opts ...grpc.CallOption) (*AssetSpendsResponse, error)
	GetRegistrations(ctx context.Context, in *RegistrationsRequest, opts ...grpc.CallOption) (*RegistrationsResponse, error)
	GetDeregistrations(ctx context.Context, in *DeregistrationsRequest, opts ...grpc.CallOption) (*DeregistrationsResponse, error)
	GetTechnicalCommitteeDatum(ctx context.Context, in *TechnicalCommitteeDatumRequest, opts ...grpc.CallOption) (*TechnicalCommitteeDatumResponse, error)
	GetCouncilDatum(ctx context.Context, in *CouncilDatumRequest, opts ...grpc.CallOption) (*CouncilDatumResponse, error)
	GetAriadneParameters(ctx context.Context, in *AriadneParametersRequest, opts ...grpc.CallOption) (*AriadneParametersResponse, error)
	GetBlockByHash(ctx context.Context, in *BlockByHashRequest, opts ...grpc.CallOption) (*BlockByHashResponse, error)
	GetUtxoEvents(ctx context.Context, in *UtxoEventsRequest, opts ...grpc.CallOption) (*UtxoEventsResponse, error)
	GetEpochNonce(ctx context.Context, in *EpochNonceRequest, opts ...grpc.CallOption) (*EpochNonceResponse, error)
	GetEpochCandidates(ctx context.Context, in *EpochCandidatesRequest, opts ...grpc.CallOption) (*EpochCandidatesResponse, error)
	GetStableBlock(ctx context.Context, in *StableBlockRequest, opts ...grpc.CallOption) (*StableBlockResponse, error)
	GetLatestStableBlock(ctx context.Context, in *LatestStableBlockRequest, opts ...grpc.CallOption) (*LatestStableBlockResponse, error)
	GetLatestBlock(ctx context.Context, in *LatestBlockRequest, opts ...grpc.CallOption) (*LatestBlockResponse, error)
}

type midnightStateClient struct {
	cc grpc.ClientConnInterface
}

func NewMidnightStateClient(cc grpc.ClientConnInterface) MidnightStateClient {
	return &midnightStateClient{cc}
}

func (c *midnightStateClient) GetAssetCreates(ctx context.Context, in *AssetCreatesRequest, opts ...grpc.CallOption) (*AssetCreatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssetCreatesResponse)
	err := c.cc.Invoke(ctx, MidnightState_GetAssetCreates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *midnightStateClient) GetAssetSpends(ctx context.Context, in *AssetSpendsRequest, opts ...grpc.CallOption) (*AssetSpendsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssetSpendsResponse)
	err := c.cc.Invoke(ctx, MidnightState_GetAssetSpends_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *midnightStateClient) GetRegistrations(ctx context.Context, in *RegistrationsRequest, opts ...grpc.CallOption) (*RegistrationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegistrationsResponse)
	err := c.cc.Invoke(ctx, MidnightState_GetRegistrations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *midnightStateClient) GetDeregistrations(ctx context.Context, in *DeregistrationsRequest, opts ...grpc.CallOption) (*DeregistrationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeregistrationsResponse)
	err := c.cc.Invoke(ctx, MidnightState_GetDeregistrations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *midnightStateClient) GetTechnicalCommitteeDatum(ctx context.Context, in *TechnicalCommitteeDatumRequest, opts ...grpc.CallOption) (*TechnicalCommitteeDatumResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TechnicalCommitteeDatumResponse)
	err := c.cc.Invoke(ctx, MidnightState_GetTechnicalCommitteeDatum_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *midnightStateClient) GetCouncilDatum(ctx context.Context, in *CouncilDatumRequest, opts ...grpc.CallOption) (*CouncilDatumResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CouncilDatumResponse)
	err := c.cc.Invoke(ctx, MidnightState_GetCouncilDatum_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *midnightStateClient) GetAriadneParameters(ctx context.Context, in *AriadneParametersRequest, opts ...grpc.CallOption) (*AriadneParametersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AriadneParametersResponse)
	err := c.cc.Invoke(ctx, MidnightState_GetAriadneParameters_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *midnightStateClient) GetBlockByHash(ctx context.Context, in *BlockByHashRequest, opts ...grpc.CallOption) (*BlockByHashResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BlockByHashResponse)
	err := c.cc.Invoke(ctx, MidnightState_GetBlockByHash_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *midnightStateClient) GetUtxoEvents(ctx context.Context, in *UtxoEventsRequest, opts ...grpc.CallOption) (*UtxoEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UtxoEventsResponse)
	err := c.cc.Invoke(ctx, MidnightState_GetUtxoEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *midnightStateClient) GetEpochNonce(ctx context.Context, in *EpochNonceRequest, opts ...grpc.CallOption) (*EpochNonceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EpochNonceResponse)
	err := c.cc.Invoke(ctx, MidnightState_GetEpochNonce_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *midnightStateClient) GetEpochCandidates(ctx context.Context, in *EpochCandidatesRequest, opts ...grpc.CallOption) (*EpochCandidatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EpochCandidatesResponse)
	err := c.cc.Invoke(ctx, MidnightState_GetEpochCandidates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *midnightStateClient) GetStableBlock(ctx context.Context, in *StableBlockRequest, opts ...grpc.CallOption) (*StableBlockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StableBlockResponse)
	err := c.cc.Invoke(ctx, MidnightState_GetStableBlock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *midnightStateClient) GetLatestStableBlock(ctx context.Context, in *LatestStableBlockRequest, opts ...grpc.CallOption) (*LatestStableBlockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LatestStableBlockResponse)
	err := c.cc.Invoke(ctx, MidnightState_GetLatestStableBlock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *midnightStateClient) GetLatestBlock(ctx context.Context, in *LatestBlockRequest, opts ...grpc.CallOption) (*LatestBlockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LatestBlockResponse)
	err := c.cc.Invoke(ctx, MidnightState_GetLatestBlock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MidnightStateServer is the server API for MidnightState service.
// All implementations must embed UnimplementedMidnightStateServer
// for forward compatibility.
type MidnightStateServer interface {
	GetAssetCreates(context.Context, *AssetCreatesRequest) (*AssetCreatesResponse, error)
	GetAssetSpends(context.Context, *AssetSpendsRequest) (*AssetSpendsResponse, error)
	GetRegistrations(context.Context, *RegistrationsRequest) (*RegistrationsResponse, error)
	GetDeregistrations(context.Context, *DeregistrationsRequest) (*DeregistrationsResponse, error)
	GetTechnicalCommitteeDatum(context.Context, *TechnicalCommitteeDatumRequest) (*TechnicalCommitteeDatumResponse, error)
	GetCouncilDatum(context.Context, *CouncilDatumRequest) (*CouncilDatumResponse, error)
	GetAriadneParameters(context.Context, *AriadneParametersRequest) (*AriadneParametersResponse, error)
	GetBlockByHash(context.Context, *BlockByHashRequest) (*BlockByHashResponse, error)
	GetUtxoEvents(context.Context, *UtxoEventsRequest) (*UtxoEventsResponse, error)
	GetEpochNonce(context.Context, *EpochNonceRequest) (*EpochNonceResponse, error)
	GetEpochCandidates(context.Context, *EpochCandidatesRequest) (*EpochCandidatesResponse, error)
	GetStableBlock(context.Context, *StableBlockRequest) (*StableBlockResponse, error)
	GetLatestStableBlock(context.Context, *LatestStableBlockRequest) (*LatestStableBlockResponse, error)
	GetLatestBlock(context.Context, *LatestBlockRequest) (*LatestBlockResponse, error)
	mustEmbedUnimplementedMidnightStateServer()
}

// UnimplementedMidnightStateServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMidnightStateServer struct{}

func (UnimplementedMidnightStateServer) GetAssetCreates(context.Context, *AssetCreatesRequest) (*AssetCreatesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAssetCreates not implemented")
}
func (UnimplementedMidnightStateServer) GetAssetSpends(context.Context, *AssetSpendsRequest) (*AssetSpendsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAssetSpends not implemented")
}
func (UnimplementedMidnightStateServer) GetRegistrations(context.Context, *RegistrationsRequest) (*RegistrationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRegistrations not implemented")
}
func (UnimplementedMidnightStateServer) GetDeregistrations(context.Context, *DeregistrationsRequest) (*DeregistrationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDeregistrations not implemented")
}
func (UnimplementedMidnightStateServer) GetTechnicalCommitteeDatum(context.Context, *TechnicalCommitteeDatumRequest) (*TechnicalCommitteeDatumResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTechnicalCommitteeDatum not implemented")
}
func (UnimplementedMidnightStateServer) GetCouncilDatum(context.Context, *CouncilDatumRequest) (*CouncilDatumResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCouncilDatum not implemented")
}
func (UnimplementedMidnightStateServer) GetAriadneParameters(context.Context, *AriadneParametersRequest) (*AriadneParametersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAriadneParameters not implemented")
}
func (UnimplementedMidnightStateServer) GetBlockByHash(context.Context, *BlockByHashRequest) (*BlockByHashResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBlockByHash not implemented")
}
func (UnimplementedMidnightStateServer) GetUtxoEvents(context.Context, *UtxoEventsRequest) (*UtxoEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUtxoEvents not implemented")
}
func (UnimplementedMidnightStateServer) GetEpochNonce(context.Context, *EpochNonceRequest) (*EpochNonceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEpochNonce not implemented")
}
func (UnimplementedMidnightStateServer) GetEpochCandidates(context.Context, *EpochCandidatesRequest) (*EpochCandidatesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEpochCandidates not implemented")
}
func (UnimplementedMidnightStateServer) GetStableBlock(context.Context, *StableBlockRequest) (*StableBlockResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStableBlock not implemented")
}
func (UnimplementedMidnightStateServer) GetLatestStableBlock(context.Context, *LatestStableBlockRequest) (*LatestStableBlockResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLatestStableBlock not implemented")
}
func (UnimplementedMidnightStateServer) GetLatestBlock(context.Context, *LatestBlockRequest) (*LatestBlockResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLatestBlock not implemented")
}
func (UnimplementedMidnightStateServer) mustEmbedUnimplementedMidnightStateServer() {}
func (UnimplementedMidnightStateServer) testEmbeddedByValue()                       {}

// UnsafeMidnightStateServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MidnightStateServer will
// result in compilation errors.
type UnsafeMidnightStateServer interface {
	mustEmbedUnimplementedMidnightStateServer()
}

func RegisterMidnightStateServer(s grpc.ServiceRegistrar, srv MidnightStateServer) {
	// If the following call panics, it indicates UnimplementedMidnightStateServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MidnightState_ServiceDesc, srv)
}

func _MidnightState_GetAssetCreates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssetCreatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MidnightStateServer).GetAssetCreates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MidnightState_GetAssetCreates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MidnightStateServer).GetAssetCreates(ctx, req.(*AssetCreatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MidnightState_GetAssetSpends_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssetSpendsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MidnightStateServer).GetAssetSpends(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MidnightState_GetAssetSpends_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MidnightStateServer).GetAssetSpends(ctx, req.(*AssetSpendsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MidnightState_GetRegistrations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegistrationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MidnightStateServer).GetRegistrations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MidnightState_GetRegistrations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MidnightStateServer).GetRegistrations(ctx, req.(*RegistrationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MidnightState_GetDeregistrations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeregistrationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MidnightStateServer).GetDeregistrations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MidnightState_GetDeregistrations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MidnightStateServer).GetDeregistrations(ctx, req.(*DeregistrationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MidnightState_GetTechnicalCommitteeDatum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TechnicalCommitteeDatumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MidnightStateServer).GetTechnicalCommitteeDatum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MidnightState_GetTechnicalCommitteeDatum_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MidnightStateServer).GetTechnicalCommitteeDatum(ctx, req.(*TechnicalCommitteeDatumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MidnightState_GetCouncilDatum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CouncilDatumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MidnightStateServer).GetCouncilDatum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MidnightState_GetCouncilDatum_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MidnightStateServer).GetCouncilDatum(ctx, req.(*CouncilDatumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MidnightState_GetAriadneParameters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AriadneParametersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MidnightStateServer).GetAriadneParameters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MidnightState_GetAriadneParameters_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MidnightStateServer).GetAriadneParameters(ctx, req.(*AriadneParametersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MidnightState_GetBlockByHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlockByHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MidnightStateServer).GetBlockByHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MidnightState_GetBlockByHash_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MidnightStateServer).GetBlockByHash(ctx, req.(*BlockByHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MidnightState_GetUtxoEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UtxoEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MidnightStateServer).GetUtxoEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MidnightState_GetUtxoEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MidnightStateServer).GetUtxoEvents(ctx, req.(*UtxoEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MidnightState_GetEpochNonce_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EpochNonceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MidnightStateServer).GetEpochNonce(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MidnightState_GetEpochNonce_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MidnightStateServer).GetEpochNonce(ctx, req.(*EpochNonceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MidnightState_GetEpochCandidates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EpochCandidatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MidnightStateServer).GetEpochCandidates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MidnightState_GetEpochCandidates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MidnightStateServer).GetEpochCandidates(ctx, req.(*EpochCandidatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MidnightState_GetStableBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StableBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MidnightStateServer).GetStableBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MidnightState_GetStableBlock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MidnightStateServer).GetStableBlock(ctx, req.(*StableBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MidnightState_GetLatestStableBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LatestStableBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MidnightStateServer).GetLatestStableBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MidnightState_GetLatestStableBlock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MidnightStateServer).GetLatestStableBlock(ctx, req.(*LatestStableBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MidnightState_GetLatestBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LatestBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MidnightStateServer).GetLatestBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MidnightState_GetLatestBlock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MidnightStateServer).GetLatestBlock(ctx, req.(*LatestBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MidnightState_ServiceDesc is the grpc.ServiceDesc for MidnightState service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MidnightState_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "midnight_state.MidnightState",
	HandlerType: (*MidnightStateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAssetCreates",
			Handler:    _MidnightState_GetAssetCreates_Handler,
		},
		{
			MethodName: "GetAssetSpends",
			Handler:    _MidnightState_GetAssetSpends_Handler,
		},
		{
			MethodName: "GetRegistrations",
			Handler:    _MidnightState_GetRegistrations_Handler,
		},
		{
			MethodName: "GetDeregistrations",
			Handler:    _MidnightState_GetDeregistrations_Handler,
		},
		{
			MethodName: "GetTechnicalCommitteeDatum",
			Handler:    _MidnightState_GetTechnicalCommitteeDatum_Handler,
		},
		{
			MethodName: "GetCouncilDatum",
			Handler:    _MidnightState_GetCouncilDatum_Handler,
		},
		{
			MethodName: "GetAriadneParameters",
			Handler:    _MidnightState_GetAriadneParameters_Handler,
		},
		{
			MethodName: "GetBlockByHash",
			Handler:    _MidnightState_GetBlockByHash_Handler,
		},
		{
			MethodName: "GetUtxoEvents",
			Handler:    _MidnightState_GetUtxoEvents_Handler,
		},
		{
			MethodName: "GetEpochNonce",
			Handler:    _MidnightState_GetEpochNonce_Handler,
		},
		{
			MethodName: "GetEpochCandidates",
			Handler:    _MidnightState_GetEpochCandidates_Handler,
		},
		{
			MethodName: "GetStableBlock",
			Handler:    _MidnightState_GetStableBlock_Handler,
		},
		{
			MethodName: "GetLatestStableBlock",
			Handler:    _MidnightState_GetLatestStableBlock_Handler,
		},
		{
			MethodName: "GetLatestBlock",
			Handler:    _MidnightState_GetLatestBlock_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "midnight/proto/midnight_state.proto",
}
