package ledger

import (
	"bytes"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"errors"
	"io"
	"testing"

	"github.com/blinklabs-io/dingo/config/cardano"
	byronconsensus "github.com/blinklabs-io/gouroboros/consensus/byron"
)

func loadByronGenesisForTest(
	t testing.TB,
	cfg *cardano.CardanoNodeConfig,
	reader io.Reader,
) error {
	t.Helper()
	data, err := io.ReadAll(reader)
	if err != nil {
		return err
	}
	defaults, err := cardano.EmbeddedConfigFS.ReadFile(
		"mainnet/byron-genesis.json",
	)
	if err != nil {
		return err
	}
	var merged, supplied map[string]json.RawMessage
	if err := json.Unmarshal(defaults, &merged); err != nil {
		return err
	}
	if err := json.Unmarshal(data, &supplied); err != nil {
		return cfg.LoadByronGenesisFromReader(bytes.NewReader(data))
	}
	for key, value := range supplied {
		if key == "blockVersionData" || key == "protocolConsts" {
			var baseObject, suppliedObject map[string]json.RawMessage
			if err := json.Unmarshal(merged[key], &baseObject); err != nil {
				return err
			}
			if err := json.Unmarshal(value, &suppliedObject); err != nil {
				return err
			}
			for nestedKey, nestedValue := range suppliedObject {
				if key == "blockVersionData" &&
					(nestedKey == "softforkRule" || nestedKey == "txFeePolicy") {
					var baseNested, suppliedNested map[string]json.RawMessage
					if err := json.Unmarshal(baseObject[nestedKey], &baseNested); err != nil {
						return err
					}
					if err := json.Unmarshal(nestedValue, &suppliedNested); err != nil {
						return err
					}
					for field, fieldValue := range suppliedNested {
						baseNested[field] = fieldValue
					}
					nestedValue, err = json.Marshal(baseNested)
					if err != nil {
						return err
					}
				}
				baseObject[nestedKey] = nestedValue
			}
			value, err = json.Marshal(baseObject)
			if err != nil {
				return err
			}
		}
		merged[key] = value
	}
	if _, hasDelegations := supplied["heavyDelegation"]; !hasDelegations {
		var protocolConsts map[string]json.RawMessage
		if err := json.Unmarshal(merged["protocolConsts"], &protocolConsts); err != nil {
			return err
		}
		protocolMagic := uint32(764824073)
		if rawMagic := protocolConsts["protocolMagic"]; len(rawMagic) > 0 {
			var value uint32
			if err := json.Unmarshal(rawMagic, &value); err != nil {
				return err
			}
			protocolMagic = value
		}
		issuer := newByronPBFTTestKey(1)
		delegate := newByronPBFTTestKey(2)
		issuerHash, err := byronconsensus.PBFTVerificationKeyHash(
			issuer.verificationKey,
		)
		if err != nil {
			return err
		}
		certificate := newSignedByronPBFTDelegationCertificate(
			t, protocolMagic, 0, issuer, delegate,
		)
		certificateSignature, ok := certificate[3].([]byte)
		if !ok {
			return errors.New("generated Byron certificate has invalid signature")
		}
		bootStakeholders, err := json.Marshal(map[string]int{
			issuerHash.String(): 1000,
		})
		if err != nil {
			return err
		}
		delegations, err := json.Marshal(map[string]any{
			issuerHash.String(): map[string]any{
				"cert":       hex.EncodeToString(certificateSignature),
				"delegatePk": base64.StdEncoding.EncodeToString(delegate.verificationKey),
				"issuerPk":   base64.StdEncoding.EncodeToString(issuer.verificationKey),
				"omega":      0,
			},
		})
		if err != nil {
			return err
		}
		merged["bootStakeholders"] = bootStakeholders
		merged["heavyDelegation"] = delegations
	}
	data, err = json.Marshal(merged)
	if err != nil {
		return err
	}
	return cfg.LoadByronGenesisFromReader(bytes.NewReader(data))
}
