#!/usr/bin/env bash
set -euo pipefail

DATABASE_URL="${DATABASE_URL:?DATABASE_URL must point to the Dingo metadata Postgres database}"
DINGO_BIN="${DINGO_BIN:-dingo}"
NETWORK="${NETWORK:-preview}"
DATA_DIR="${CARDANO_DATABASE_PATH:-${PWD}/.dingo-preview}"

export CARDANO_DATABASE_PATH="${DATA_DIR}"
export DINGO_STORAGE_MODE="${DINGO_STORAGE_MODE:-api}"
export DINGO_DATABASE_METADATA_PLUGIN="${DINGO_DATABASE_METADATA_PLUGIN:-postgres}"
export DINGO_DATABASE_METADATA_POSTGRES_DSN="${DINGO_DATABASE_METADATA_POSTGRES_DSN:-${DATABASE_URL}}"
export DINGO_DATABASE_BLOB_PLUGIN="${DINGO_DATABASE_BLOB_PLUGIN:-badger}"
export DINGO_BLOCKFROST_PORT="${DINGO_BLOCKFROST_PORT:-0}"
export DINGO_MESH_PORT="${DINGO_MESH_PORT:-0}"
export DINGO_UTXORPC_PORT="${DINGO_UTXORPC_PORT:-0}"

exec "${DINGO_BIN}" -n "${NETWORK}" mithril sync
