FROM ghcr.io/blinklabs-io/go:1.25.7-1 AS build

WORKDIR /code
RUN go env -w GOCACHE=/go-cache
RUN go env -w GOMODCACHE=/gomod-cache
COPY go.* .
RUN --mount=type=cache,target=/gomod-cache go mod download
COPY . .
RUN --mount=type=cache,target=/gomod-cache --mount=type=cache,target=/go-cache \
    go build -o txpump ./cmd/txpump/

FROM debian:bookworm-slim
RUN apt-get update -y && \
    apt-get install -y --no-install-recommends ca-certificates && \
    rm -rf /var/lib/apt/lists/*
RUN useradd -m txpump
COPY --from=build /code/txpump /bin/txpump
USER txpump
ENTRYPOINT ["/bin/txpump"]
