// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlitequery

import (
	"database/sql"

	"github.com/blinklabs-io/dingo/database/types"
)

type Account struct {
	StakingKey      []byte
	CredentialTag   int64
	Pool            []byte
	Drep            []byte
	ID              int64
	AddedSlot       sql.NullInt64
	CreatedSlot     int64
	CertificateID   sql.NullInt64
	Reward          sql.NullString
	DrepType        sql.NullInt64
	Active          sql.NullBool
	ExpirationEpoch sql.NullInt64
}

type AddressTransaction struct {
	ID            int64
	PaymentKey    []byte
	StakingKey    []byte
	CredentialTag int64
	TransactionID sql.NullInt64
	Slot          sql.NullInt64
	TxIndex       sql.NullInt64
}

type Asset struct {
	Name        []byte
	NameHex     []byte
	PolicyID    []byte
	Fingerprint []byte
	ID          int64
	UtxoID      sql.NullInt64
	Amount      sql.NullString
}

type AssetMintBurn struct {
	ID          int64
	TxHash      []byte
	PolicyID    []byte
	Name        []byte
	Fingerprint []byte
	Slot        sql.NullInt64
	Quantity    sql.NullString
	TxIndex     sql.NullInt64
}

type BackfillCheckpoint struct {
	ID         int64
	Phase      string
	LastSlot   sql.NullInt64
	TotalSlots sql.NullInt64
	StartedAt  sql.NullTime
	UpdatedAt  sql.NullTime
	Completed  sql.NullBool
}

type BlockNonce struct {
	Hash         []byte
	Nonce        []byte
	ID           int64
	Slot         sql.NullInt64
	IsCheckpoint sql.NullBool
}

type CommitTimestamp struct {
	ID        int64
	Timestamp sql.NullInt64
}

type CommitteeMember struct {
	ID           int64
	ColdCredHash []byte
	ExpiresEpoch int64
	AddedSlot    int64
	DeletedSlot  sql.NullInt64
}

type CommitteeQuorum struct {
	Quorum    sql.NullString
	ID        int64
	AddedSlot int64
}

type Constitution struct {
	ID          int64
	AnchorUrl   string
	AnchorHash  []byte
	PolicyHash  []byte
	AddedSlot   int64
	DeletedSlot sql.NullInt64
}

type Datum struct {
	Hash      []byte
	RawDatum  []byte
	ID        int64
	AddedSlot int64
}

type Drep struct {
	AnchorUrl         sql.NullString
	Credential        []byte
	AnchorHash        []byte
	ID                int64
	AddedSlot         sql.NullInt64
	CredentialTag     int64
	LastActivityEpoch sql.NullInt64
	ExpiryEpoch       sql.NullInt64
	Active            sql.NullBool
}

type Epoch struct {
	Nonce               []byte
	EvolvingNonce       []byte
	CandidateNonce      []byte
	LastEpochBlockNonce []byte
	ID                  int64
	EpochID             sql.NullInt64
	StartSlot           sql.NullInt64
	EraID               sql.NullInt64
	SlotLength          sql.NullInt64
	LengthInSlots       sql.NullInt64
}

type EpochSummary struct {
	ID               int64
	Epoch            int64
	TotalActiveStake string
	TotalPoolCount   int64
	TotalDelegators  int64
	EpochNonce       []byte
	BoundarySlot     int64
	SnapshotReady    bool
}

type ImportCheckpoint struct {
	ID        int64
	ImportKey string
	Phase     string
}

type MidnightAriadneParam struct {
	ID    int64
	Epoch int64
	Datum []byte
}

type MidnightAriadneRollback struct {
	ID             int64
	BlockNumber    int64
	Epoch          int64
	PreviousExists bool
	PreviousDatum  []byte
}

type MidnightAssetCreate struct {
	ID               int64
	Address          []byte
	Quantity         int64
	TxHash           []byte
	OutputIndex      int64
	BlockNumber      int64
	BlockHash        []byte
	TxIndex          int64
	BlockTimestampMs int64
}

type MidnightAssetSpend struct {
	ID               int64
	Address          []byte
	Quantity         int64
	SpendingTxHash   []byte
	UtxoTxHash       []byte
	UtxoIndex        int64
	BlockNumber      int64
	BlockHash        []byte
	TxIndex          int64
	BlockTimestampMs int64
}

type MidnightCommitteeCandidateRegistration struct {
	ID           int64
	TxHash       []byte
	OutputIndex  int64
	BlockNumber  int64
	SlotNumber   int64
	TxIndex      int64
	TxInputsCbor []byte
}

type MidnightDeregistration struct {
	ID               int64
	FullDatum        []byte
	TxHash           []byte
	UtxoTxHash       []byte
	UtxoIndex        int64
	BlockNumber      int64
	BlockHash        []byte
	TxIndex          int64
	BlockTimestampMs int64
}

type MidnightEpochCandidate struct {
	ID             int64
	Epoch          int64
	BlockNumber    int64
	CandidatesCbor []byte
}

type MidnightGovernanceDatum struct {
	ID          int64
	DatumType   string
	TxHash      []byte
	OutputIndex int64
	Datum       []byte
	BlockNumber int64
}

type MidnightRegistration struct {
	ID               int64
	FullDatum        []byte
	TxHash           []byte
	OutputIndex      int64
	BlockNumber      int64
	BlockHash        []byte
	TxIndex          int64
	BlockTimestampMs int64
}

type NetworkDonation struct {
	ID     int64
	Slot   int64
	Epoch  int64
	Amount int64
}

type NetworkState struct {
	ID       int64
	Treasury string
	Reserves string
	Slot     int64
}

type NodeSetting struct {
	ID          int64
	StorageMode string
	Network     string
}

type NodeSettingsGate struct {
	Name          string
	Value         string
	RecordedEpoch int64
	RecordedSlot  int64
}

type OffchainMetadatum struct {
	FetchedAt      sql.NullTime
	NextFetchAfter sql.NullTime
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
	Url            string
	SourceType     string
	Status         string
	ContentType    sql.NullString
	LastError      sql.NullString
	Hash           []byte
	BodyHash       []byte
	Content        []byte
	ID             int64
	FetchAttempts  sql.NullInt64
	LastHttpStatus sql.NullInt64
}

type PoolStakeSnapshot struct {
	ID                            int64
	Epoch                         int64
	SnapshotType                  string
	PoolKeyHash                   []byte
	TotalStake                    string
	StakeDenominator              string
	DelegatorCount                int64
	CapturedSlot                  int64
	CalculationVersion            int64
	RewardAccountAutoVote         int64
	RewardAccountAutoVoteResolved bool
}

type Pparam struct {
	Cbor      []byte
	ID        int64
	AddedSlot sql.NullInt64
	Epoch     sql.NullInt64
	EraID     sql.NullInt64
}

type PparamUpdate struct {
	GenesisHash []byte
	Cbor        []byte
	ID          int64
	AddedSlot   sql.NullInt64
	Epoch       sql.NullInt64
}

type RegistrationDrep struct {
	AnchorUrl      sql.NullString
	DrepCredential []byte
	AnchorHash     []byte
	CertificateID  sql.NullInt64
	ID             int64
	CredentialTag  int64
	AddedSlot      sql.NullInt64
	DepositAmount  sql.NullString
}

type RewardAccountOutput struct {
	StakingKey    []byte
	PoolKeyHash   []byte
	RewardType    string
	ID            int64
	Epoch         int64
	CredentialTag int64
	Amount        string
	Spendable     bool
	Guarded       bool
	CapturedSlot  int64
	BoundarySlot  int64
}

type RewardAdaPot struct {
	ID           int64
	Epoch        int64
	Treasury     string
	Reserves     string
	Fees         string
	Rewards      string
	CapturedSlot int64
}

type RewardPoolInput struct {
	Margin                     sql.NullString
	PoolKeyHash                []byte
	RewardAccount              []byte
	BlocksProduced             sql.NullInt64
	TotalBlocksInEpoch         sql.NullInt64
	ID                         int64
	Epoch                      int64
	Pledge                     string
	DelegatedStake             string
	OwnerStake                 string
	Cost                       string
	DelegatorCount             int64
	RewardAccountCredentialTag int64
	CapturedSlot               int64
	BoundarySlot               int64
}

type RewardPoolOutput struct {
	ApparentPerformance sql.NullString
	PoolKeyHash         []byte
	ID                  int64
	Epoch               int64
	OptimalReward       string
	TotalReward         string
	LeaderReward        string
	MemberRewardTotal   string
	OwnerStake          string
	Undistributed       string
	Unspendable         string
	CapturedSlot        int64
	BoundarySlot        int64
}

type RewardSnapshot struct {
	ID                 int64
	Epoch              int64
	SnapshotType       string
	TotalActiveStake   string
	TotalPoolCount     int64
	TotalDelegators    int64
	CapturedSlot       int64
	BoundarySlot       int64
	EpochNonce         []byte
	ProtocolVersion    int64
	Authoritative      bool
	CalculationVersion int64
}

type RewardStakeInput struct {
	PoolKeyHash   []byte
	StakingKey    []byte
	ID            int64
	Epoch         int64
	CredentialTag int64
	Stake         string
	Owner         bool
	Registered    bool
	CapturedSlot  int64
	BoundarySlot  int64
}

type Script struct {
	Hash        []byte
	Content     []byte
	ID          int64
	CreatedSlot sql.NullInt64
	Type        sql.NullInt64
}

type SyncState struct {
	SyncKey string
	Value   string
}

type Tip struct {
	Hash        []byte
	ID          int64
	Slot        sql.NullInt64
	BlockNumber sql.NullInt64
}

type Transaction struct {
	Hash          []byte
	BlockHash     []byte
	Metadata      []byte
	Slot          sql.NullInt64
	Type          sql.NullInt64
	ID            int64
	Fee           sql.NullString
	CollateralFee sql.NullString
	Ttl           sql.NullString
	BlockIndex    sql.NullInt64
	Valid         sql.NullBool
}

type TransactionMetadataLabel struct {
	ID            int64
	TransactionID sql.NullInt64
	Label         sql.NullString
	Slot          sql.NullInt64
	CborValue     []byte
	JsonValue     sql.NullString
}

type Utxo struct {
	TransactionID           sql.NullInt64
	CollateralReturnForTxID sql.NullInt64
	TxID                    []byte
	PaymentKey              []byte
	StakingKey              []byte
	CredentialTag           int64
	DatumHash               []byte
	SpentAtTxID             types.NullableHash
	ReferencedByTxID        types.NullableHash
	CollateralByTxID        types.NullableHash
	ID                      int64
	AddedSlot               sql.NullInt64
	DeletedSlot             sql.NullInt64
	Amount                  sql.NullString
	OutputIdx               sql.NullInt64
	PaymentScript           sql.NullBool
}
