// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlitequery

import (
	"context"
	"database/sql"
)

type Querier interface {
	AddNetworkDonation(ctx context.Context, arg AddNetworkDonationParams) error
	BackfillNodeSettingsNetwork(ctx context.Context, arg BackfillNodeSettingsNetworkParams) (int64, error)
	ClaimOffchainMetadataFetch(ctx context.Context, arg ClaimOffchainMetadataFetchParams) (int64, error)
	ClearSyncState(ctx context.Context) error
	CountTransactionsByMetadataLabel(ctx context.Context, label sql.NullString) (int64, error)
	CountTransactionsByPaymentCred(ctx context.Context, paymentKey []byte) (int64, error)
	CountTransactionsInSlotRange(ctx context.Context, arg CountTransactionsInSlotRangeParams) (int64, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (int64, error)
	CreateAsset(ctx context.Context, arg CreateAssetParams) (int64, error)
	CreateDrep(ctx context.Context, arg CreateDrepParams) (int64, error)
	CreateMidnightAriadneRollback(ctx context.Context, arg CreateMidnightAriadneRollbackParams) (int64, error)
	CreateMidnightAssetCreate(ctx context.Context, arg CreateMidnightAssetCreateParams) (int64, error)
	CreateMidnightAssetSpend(ctx context.Context, arg CreateMidnightAssetSpendParams) (int64, error)
	CreateMidnightDeregistration(ctx context.Context, arg CreateMidnightDeregistrationParams) (int64, error)
	CreateMidnightRegistration(ctx context.Context, arg CreateMidnightRegistrationParams) (int64, error)
	CreatePoolStakeSnapshot(ctx context.Context, arg CreatePoolStakeSnapshotParams) (int64, error)
	CreateUtxo(ctx context.Context, arg CreateUtxoParams) (int64, error)
	CreateUtxoIfAbsent(ctx context.Context, arg CreateUtxoIfAbsentParams) (int64, error)
	DeleteAddressTransactionsAfterSlot(ctx context.Context, slot sql.NullInt64) error
	DeleteBlockNoncesAfterOrigin(ctx context.Context, slot sql.NullInt64) error
	DeleteBlockNoncesAfterPoint(ctx context.Context, arg DeleteBlockNoncesAfterPointParams) error
	DeleteBlockNoncesBeforeSlot(ctx context.Context, slot sql.NullInt64) error
	DeleteBlockNoncesBeforeSlotWithoutCheckpoints(ctx context.Context, slot sql.NullInt64) error
	DeleteCommitteeMembersAddedAfterSlot(ctx context.Context, addedSlot int64) error
	DeleteCommitteeQuorumsAfterSlot(ctx context.Context, addedSlot int64) error
	DeleteConstitutionsAddedAfterSlot(ctx context.Context, addedSlot int64) error
	DeleteEpochSummariesAfterEpoch(ctx context.Context, epoch int64) error
	DeleteEpochsAfterSlot(ctx context.Context, startSlot sql.NullInt64) error
	DeleteMidnightAriadneParamsByEpoch(ctx context.Context, epoch int64) error
	DeleteMidnightAriadneRollbacksBeforeBlock(ctx context.Context, blockNumber int64) error
	DeleteMidnightAriadneRollbacksByBlock(ctx context.Context, blockNumber int64) error
	DeleteMidnightAssetCreatesByBlock(ctx context.Context, blockNumber int64) error
	DeleteMidnightAssetSpendsByBlock(ctx context.Context, blockNumber int64) error
	DeleteMidnightCommitteeCandidateRegistrationsByBlock(ctx context.Context, blockNumber int64) error
	DeleteMidnightDeregistrationsByBlock(ctx context.Context, blockNumber int64) error
	DeleteMidnightEpochCandidatesByBlock(ctx context.Context, blockNumber int64) error
	DeleteMidnightGovernanceDatumsByBlock(ctx context.Context, blockNumber int64) error
	DeleteMidnightRegistrationsByBlock(ctx context.Context, blockNumber int64) error
	DeleteNetworkDonationsAfterSlot(ctx context.Context, slot int64) error
	DeleteNetworkStateAfterSlot(ctx context.Context, slot int64) error
	DeletePParamUpdatesAfterSlot(ctx context.Context, addedSlot sql.NullInt64) error
	DeletePParamsAfterSlot(ctx context.Context, addedSlot sql.NullInt64) error
	DeletePoolStakeSnapshotsAfterEpoch(ctx context.Context, epoch int64) error
	DeletePoolStakeSnapshotsBeforeEpoch(ctx context.Context, epoch int64) error
	DeletePoolStakeSnapshotsForEpoch(ctx context.Context, arg DeletePoolStakeSnapshotsForEpochParams) error
	DeleteRewardAccountOutputsAfterSlot(ctx context.Context, arg DeleteRewardAccountOutputsAfterSlotParams) error
	DeleteRewardAccountOutputsBeforeEpoch(ctx context.Context, epoch int64) error
	DeleteRewardAccountOutputsForEpoch(ctx context.Context, epoch int64) error
	DeleteRewardAdaPotsAfterSlot(ctx context.Context, capturedSlot int64) error
	DeleteRewardPoolInputsAfterSlot(ctx context.Context, arg DeleteRewardPoolInputsAfterSlotParams) error
	DeleteRewardPoolInputsForEpoch(ctx context.Context, epoch int64) error
	DeleteRewardPoolOutputsAfterSlot(ctx context.Context, arg DeleteRewardPoolOutputsAfterSlotParams) error
	DeleteRewardPoolOutputsForEpoch(ctx context.Context, epoch int64) error
	DeleteRewardSnapshotsAfterSlot(ctx context.Context, arg DeleteRewardSnapshotsAfterSlotParams) error
	DeleteRewardStakeInputsAfterSlot(ctx context.Context, arg DeleteRewardStakeInputsAfterSlotParams) error
	DeleteRewardStakeInputsBeforeEpoch(ctx context.Context, epoch int64) error
	DeleteRewardStakeInputsForEpoch(ctx context.Context, epoch int64) error
	DeleteSyncState(ctx context.Context, syncKey string) error
	DeleteTransactionMetadataLabelsAfterSlot(ctx context.Context, slot sql.NullInt64) error
	FindMidnightAriadneRollbacksByBlock(ctx context.Context, blockNumber int64) ([]MidnightAriadneRollback, error)
	FindUnspentMidnightAssetCreates(ctx context.Context) ([]MidnightAssetCreate, error)
	FindUnspentMidnightRegistrations(ctx context.Context) ([]MidnightRegistration, error)
	GetAccountByCredential(ctx context.Context, arg GetAccountByCredentialParams) (Account, error)
	GetActiveAccountByCredential(ctx context.Context, arg GetActiveAccountByCredentialParams) (Account, error)
	GetActiveDrepByCredential(ctx context.Context, arg GetActiveDrepByCredentialParams) (Drep, error)
	GetActiveDrepByHash(ctx context.Context, credential []byte) (Drep, error)
	GetActiveDreps(ctx context.Context) ([]Drep, error)
	GetAssetByPolicyAndName(ctx context.Context, arg GetAssetByPolicyAndNameParams) (Asset, error)
	GetAssetMintBurnInfo(ctx context.Context, arg GetAssetMintBurnInfoParams) (GetAssetMintBurnInfoRow, error)
	GetAssetQuantityByPolicyAndName(ctx context.Context, arg GetAssetQuantityByPolicyAndNameParams) ([]sql.NullString, error)
	GetAssetsByUtxoID(ctx context.Context, utxoID sql.NullInt64) ([]Asset, error)
	GetBackfillCheckpoint(ctx context.Context, phase string) (BackfillCheckpoint, error)
	GetBlockNonce(ctx context.Context, arg GetBlockNonceParams) ([]byte, error)
	GetBlockNoncesInSlotRange(ctx context.Context, arg GetBlockNoncesInSlotRangeParams) ([]BlockNonce, error)
	GetBlockSlotRangeStats(ctx context.Context, arg GetBlockSlotRangeStatsParams) (GetBlockSlotRangeStatsRow, error)
	GetCommitTimestamp(ctx context.Context) (sql.NullInt64, error)
	GetCommitteeMembers(ctx context.Context) ([]CommitteeMember, error)
	GetCommitteeMembersIncludeDeleted(ctx context.Context) ([]CommitteeMember, error)
	GetCommitteeQuorum(ctx context.Context) (sql.NullString, error)
	GetConstitution(ctx context.Context) (Constitution, error)
	GetControlledAmountByCredential(ctx context.Context, arg GetControlledAmountByCredentialParams) ([]sql.NullString, error)
	GetDRepDelegators(ctx context.Context, arg GetDRepDelegatorsParams) ([]GetDRepDelegatorsRow, error)
	GetDatum(ctx context.Context, hash []byte) (Datum, error)
	GetDrepByCredential(ctx context.Context, arg GetDrepByCredentialParams) (Drep, error)
	GetDrepByHash(ctx context.Context, credential []byte) (Drep, error)
	GetDrepLastRegistrationSlot(ctx context.Context, arg GetDrepLastRegistrationSlotParams) (int64, error)
	GetEpoch(ctx context.Context, epochID sql.NullInt64) (GetEpochRow, error)
	GetEpochBySlot(ctx context.Context, arg GetEpochBySlotParams) (GetEpochBySlotRow, error)
	GetEpochSummary(ctx context.Context, epoch int64) (EpochSummary, error)
	GetEpochs(ctx context.Context) ([]GetEpochsRow, error)
	GetEpochsByEra(ctx context.Context, eraID sql.NullInt64) ([]GetEpochsByEraRow, error)
	GetExpiredDReps(ctx context.Context, expiryEpoch sql.NullInt64) ([]Drep, error)
	GetImportCheckpoint(ctx context.Context, importKey string) (ImportCheckpoint, error)
	GetLastBlockNonceInRange(ctx context.Context, arg GetLastBlockNonceInRangeParams) ([]byte, error)
	GetLatestEpochSummary(ctx context.Context) (EpochSummary, error)
	GetLatestMidnightAriadneParams(ctx context.Context) (MidnightAriadneParam, error)
	GetLatestMidnightGovernanceDatum(ctx context.Context, arg GetLatestMidnightGovernanceDatumParams) (MidnightGovernanceDatum, error)
	GetLatestNetworkState(ctx context.Context) (NetworkState, error)
	GetLiveUtxo(ctx context.Context, arg GetLiveUtxoParams) (Utxo, error)
	GetLiveUtxoRefsBySlot(ctx context.Context, addedSlot sql.NullInt64) ([]GetLiveUtxoRefsBySlotRow, error)
	GetLiveUtxosByAsset(ctx context.Context, arg GetLiveUtxosByAssetParams) ([]Utxo, error)
	GetLiveUtxosByAssetPolicy(ctx context.Context, policyID []byte) ([]Utxo, error)
	GetMidnightAriadneParamsAtOrBeforeEpoch(ctx context.Context, epoch int64) (MidnightAriadneParam, error)
	GetMidnightAriadneParamsByEpoch(ctx context.Context, epoch int64) (MidnightAriadneParam, error)
	GetMidnightAssetCreatesByBlock(ctx context.Context, blockNumber int64) ([]MidnightAssetCreate, error)
	GetMidnightAssetSpendsByBlock(ctx context.Context, blockNumber int64) ([]MidnightAssetSpend, error)
	GetMidnightDeregistrationsByBlock(ctx context.Context, blockNumber int64) ([]MidnightDeregistration, error)
	GetMidnightEpochCandidatesByEpoch(ctx context.Context, epoch int64) (MidnightEpochCandidate, error)
	GetMidnightRegistrationsByBlock(ctx context.Context, blockNumber int64) ([]MidnightRegistration, error)
	GetNodeSettings(ctx context.Context) (GetNodeSettingsRow, error)
	GetNodeSettingsGates(ctx context.Context) ([]GetNodeSettingsGatesRow, error)
	GetOffchainMetadata(ctx context.Context, arg GetOffchainMetadataParams) (OffchainMetadatum, error)
	GetOffchainMetadataFetchCandidates(ctx context.Context, arg GetOffchainMetadataFetchCandidatesParams) ([]OffchainMetadatum, error)
	GetPParamUpdates(ctx context.Context, arg GetPParamUpdatesParams) ([]PparamUpdate, error)
	GetPParams(ctx context.Context, arg GetPParamsParams) ([]Pparam, error)
	GetPoolStakeSnapshot(ctx context.Context, arg GetPoolStakeSnapshotParams) (PoolStakeSnapshot, error)
	GetPoolStakeSnapshotsByEpoch(ctx context.Context, arg GetPoolStakeSnapshotsByEpochParams) ([]PoolStakeSnapshot, error)
	GetRewardAccountOutputs(ctx context.Context, epoch int64) ([]RewardAccountOutput, error)
	GetRewardAdaPots(ctx context.Context, epoch int64) (RewardAdaPot, error)
	GetRewardPoolInputs(ctx context.Context, epoch int64) ([]RewardPoolInput, error)
	GetRewardPoolOutputs(ctx context.Context, epoch int64) ([]RewardPoolOutput, error)
	GetRewardSnapshot(ctx context.Context, arg GetRewardSnapshotParams) (RewardSnapshot, error)
	GetRewardStakeInputs(ctx context.Context, epoch int64) ([]RewardStakeInput, error)
	GetScript(ctx context.Context, hash []byte) (Script, error)
	GetScriptLockedSupply(ctx context.Context) ([]sql.NullString, error)
	GetSyncState(ctx context.Context, syncKey string) (string, error)
	GetTip(ctx context.Context) (GetTipRow, error)
	GetTransactionByHash(ctx context.Context, hash []byte) (Transaction, error)
	GetTransactionHashesAfterSlot(ctx context.Context, slot sql.NullInt64) ([][]byte, error)
	GetTransactionIDByHash(ctx context.Context, hash []byte) (int64, error)
	GetTransactionMetadataByHash(ctx context.Context, hash []byte) ([]byte, error)
	GetTransactionSlotByHash(ctx context.Context, hash []byte) (sql.NullInt64, error)
	GetTransactionsByBlockHash(ctx context.Context, blockHash []byte) ([]Transaction, error)
	GetUtxoIDByRef(ctx context.Context, arg GetUtxoIDByRefParams) (int64, error)
	GetUtxoIncludingSpent(ctx context.Context, arg GetUtxoIncludingSpentParams) (Utxo, error)
	GetUtxoRefsBySlot(ctx context.Context, addedSlot sql.NullInt64) ([]GetUtxoRefsBySlotRow, error)
	GetUtxosAddedAfterSlot(ctx context.Context, addedSlot sql.NullInt64) ([]Utxo, error)
	GetUtxosDeletedBeforeSlot(ctx context.Context, arg GetUtxosDeletedBeforeSlotParams) ([]Utxo, error)
	ImportAccount(ctx context.Context, arg ImportAccountParams) (int64, error)
	ImportAsset(ctx context.Context, arg ImportAssetParams) error
	ImportDrep(ctx context.Context, arg ImportDrepParams) (int64, error)
	ImportDrepRegistration(ctx context.Context, arg ImportDrepRegistrationParams) (int64, error)
	InsertDrepIfAbsent(ctx context.Context, arg InsertDrepIfAbsentParams) error
	InsertMidnightCommitteeCandidateRegistration(ctx context.Context, arg InsertMidnightCommitteeCandidateRegistrationParams) (int64, error)
	InsertMidnightGovernanceDatum(ctx context.Context, arg InsertMidnightGovernanceDatumParams) (int64, error)
	InsertNodeSettings(ctx context.Context, arg InsertNodeSettingsParams) (int64, error)
	InsertOffchainMetadataPointer(ctx context.Context, arg InsertOffchainMetadataPointerParams) (int64, error)
	InsertRewardSnapshot(ctx context.Context, arg InsertRewardSnapshotParams) (int64, error)
	ReleaseFallbackRewardSnapshotGuard(ctx context.Context, id int64) (int64, error)
	RestoreCommitteeMembersDeletedAfterSlot(ctx context.Context, deletedSlot sql.NullInt64) error
	RestoreConstitutionsDeletedAfterSlot(ctx context.Context, deletedSlot sql.NullInt64) error
	SaveEpochSummary(ctx context.Context, arg SaveEpochSummaryParams) (int64, error)
	SavePoolStakeSnapshot(ctx context.Context, arg SavePoolStakeSnapshotParams) (int64, error)
	SaveRewardAccountOutput(ctx context.Context, arg SaveRewardAccountOutputParams) (int64, error)
	SaveRewardAdaPots(ctx context.Context, arg SaveRewardAdaPotsParams) (int64, error)
	SaveRewardPoolInput(ctx context.Context, arg SaveRewardPoolInputParams) (int64, error)
	SaveRewardPoolOutput(ctx context.Context, arg SaveRewardPoolOutputParams) (int64, error)
	SaveRewardSnapshot(ctx context.Context, arg SaveRewardSnapshotParams) (int64, error)
	SaveRewardStakeInput(ctx context.Context, arg SaveRewardStakeInputParams) (int64, error)
	SetBackfillCheckpoint(ctx context.Context, arg SetBackfillCheckpointParams) (int64, error)
	SetBlockNonce(ctx context.Context, arg SetBlockNonceParams) error
	SetCommitTimestamp(ctx context.Context, timestamp sql.NullInt64) error
	SetCommitteeMember(ctx context.Context, arg SetCommitteeMemberParams) (int64, error)
	SetCommitteeQuorum(ctx context.Context, arg SetCommitteeQuorumParams) error
	SetConstitution(ctx context.Context, arg SetConstitutionParams) (int64, error)
	SetDatum(ctx context.Context, arg SetDatumParams) error
	SetDrep(ctx context.Context, arg SetDrepParams) error
	SetEpoch(ctx context.Context, arg SetEpochParams) error
	SetImportCheckpoint(ctx context.Context, arg SetImportCheckpointParams) error
	SetNetworkState(ctx context.Context, arg SetNetworkStateParams) error
	SetOffchainMetadataFetchResult(ctx context.Context, arg SetOffchainMetadataFetchResultParams) error
	SetPParamUpdate(ctx context.Context, arg SetPParamUpdateParams) error
	SetPParams(ctx context.Context, arg SetPParamsParams) error
	SetSyncState(ctx context.Context, arg SetSyncStateParams) error
	SetTip(ctx context.Context, arg SetTipParams) error
	SoftDeleteAllCommitteeMembers(ctx context.Context, deletedSlot sql.NullInt64) error
	SoftDeleteCommitteeMember(ctx context.Context, arg SoftDeleteCommitteeMemberParams) error
	SumPoolStakeSnapshots(ctx context.Context, arg SumPoolStakeSnapshotsParams) ([]string, error)
	SumTransactionFeesInSlotRange(ctx context.Context, arg SumTransactionFeesInSlotRangeParams) ([]interface{}, error)
	UpdateDRepActivity(ctx context.Context, arg UpdateDRepActivityParams) (int64, error)
	UpdateFallbackRewardSnapshot(ctx context.Context, arg UpdateFallbackRewardSnapshotParams) (int64, error)
	UpsertMidnightAriadneParams(ctx context.Context, arg UpsertMidnightAriadneParamsParams) (int64, error)
	UpsertMidnightEpochCandidates(ctx context.Context, arg UpsertMidnightEpochCandidatesParams) (int64, error)
	UpsertNodeSettingsGate(ctx context.Context, arg UpsertNodeSettingsGateParams) error
}

var _ Querier = (*Queries)(nil)
