// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package mysqlquery

import (
	"context"
	"database/sql"
)

type Querier interface {
	BackfillNodeSettingsNetwork(ctx context.Context, arg BackfillNodeSettingsNetworkParams) (int64, error)
	GetCommitTimestamp(ctx context.Context) (sql.NullInt64, error)
	GetNodeSettings(ctx context.Context) (GetNodeSettingsRow, error)
	GetNodeSettingsGates(ctx context.Context) ([]GetNodeSettingsGatesRow, error)
	InsertNodeSettings(ctx context.Context, arg InsertNodeSettingsParams) (int64, error)
	// INSERT IGNORE, not the ON DUPLICATE KEY UPDATE ... = VALUES(...) pattern
	// used above: that pattern always performs an UPDATE, whose RowsAffected is
	// ambiguous on a duplicate (0 normally, 1 under the driver's
	// CLIENT_FOUND_ROWS mode -- see SetNodeSettings's doc comment for the same
	// caveat). INSERT IGNORE either inserts or does nothing; RowsAffected is 1
	// or 0 with no such ambiguity, since no UPDATE ever runs.
	InsertNodeSettingsGateIfAbsent(ctx context.Context, arg InsertNodeSettingsGateIfAbsentParams) (int64, error)
	SetCommitTimestamp(ctx context.Context, timestamp sql.NullInt64) error
	UpsertNodeSettingsGate(ctx context.Context, arg UpsertNodeSettingsGateParams) error
}

var _ Querier = (*Queries)(nil)
