// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package mysqlquery

import (
	"context"
	"database/sql"
)

type Querier interface {
	BackfillNodeSettingsNetwork(ctx context.Context, arg BackfillNodeSettingsNetworkParams) (int64, error)
	GetCommitTimestamp(ctx context.Context) (sql.NullInt64, error)
	GetNodeSettings(ctx context.Context) (GetNodeSettingsRow, error)
	GetNodeSettingsGates(ctx context.Context) ([]GetNodeSettingsGatesRow, error)
	InsertNodeSettings(ctx context.Context, arg InsertNodeSettingsParams) (int64, error)
	SetCommitTimestamp(ctx context.Context, timestamp sql.NullInt64) error
	UpsertNodeSettingsGate(ctx context.Context, arg UpsertNodeSettingsGateParams) error
}

var _ Querier = (*Queries)(nil)
