name: Test Issue Close Trigger

on:
  issues:
    types: [closed]

permissions:
  contents: read

jobs:
  test:
    uses: blinklabs-io/actions/.github/workflows/reuseable-test-issue-on-close.yml@main
    with:
      issue_number: ${{ github.event.issue.number }}
      issue_title: ${{ github.event.issue.title }}